localstack/docs

- content/en/aws/managed-streaming-for-kafka/index.md
- content/en/aws/multi-account-setups/index.md
- package-lock.json
MSK documentation with create and describe cluster examples
> MSK documentation

- content/en/integrations/pulumi/index.md
- content/en/integrations/terraform/index.md
Followup for https://github.com/localstack/localstack/issues/5051 and https://localstack-community.slack.com/archives/CMAFN2KSP/p1638976319054900
> add apigatewayv2 to pulumi and terraform

- content/en/tools/analytics-dashboard/index.md
> docs: Improve documentation on browser compatibility with dashboard

- content/en/localstack/podman/index.md
Requires https://github.com/localstack/localstack/pull/5124
Related to my `podman` exploration: https://github.com/localstack/localstack/pull/5116
> add howto for podman

- .github/workflows/lint.yml
- .github/workflows/markdown.links.config.json
- content/en/integrations/serverless-framework/index.md
- content/en/integrations/spring-cloud-function/index.md
- content/en/tools/lambda-tools/hot-swapping/index.md
This PR:
- Adds a GHA to look for broken links
- Fix noticeable broken links
> CI: Add broken link checker for docs

- content/en/aws/systems-manager/index.md
Depends on https://github.com/localstack/localstack-ext/pull/391
> Add docs for AWS SSM

- content/en/localstack/limitations.md
> corrected spelling

- content/en/aws/appsync/index.md
Part of https://github.com/localstack/localstack-ext/pull/430
> Add docs for using custom IDs for GraphQL APIs

- content/en/aws/cognito/index.md
> Clarify OAuth2 docs

- .github/workflows/markdown.links.config.json
- README.md
This PR revises the `README.md` a bit.
It adds a more verbose description on how to setup the dev environment and adds a section on tackling common issues (the submodules tend to cause a bit of confusion).
> revise README

- content/en/aws/elastic-compute-cloud/index.md
To be merged after https://github.com/localstack/localstack-ext/pull/429
> EC2: Add UserData, KeyPairs, DIND

- content/en/integrations/terraform/index.md
Add initial instructions for using the `tflocal` script to deploy Terraform resources locally.
> Add initial instructions for using tflocal

- content/en/developer-guide/setup.md
Add different packages for Fedora Installations.
> Add Fedora installation in the Setup Dev Guide

- content/en/localstack/configuration.md
Fixes https://github.com/localstack/docs/issues/114
> DOCS: Add EAGER_SERVICE_LOADING to configuration page

- content/en/aws/elastic-compute-cloud/index.md
- content/en/aws/elastic-load-balancing/index.md
Add a basic walkthrough of using ELB targetting an IP address
> Add docs for ELB

- content/en/aws/elastic-kubernetes-service/index.md
- content/en/localstack/configuration.md
Extend EKS docs to include Ingress configuration.
> Extend EKS docs to include Ingress configuration

- content/en/localstack/configuration.md
Adding the LAMBDA_TRUNCATE_STDOUT to configuration page.
> Add LAMBDA_TRUNCATE_STDOUT

- content/en/aws/s3/index.md
> Closing brace

- content/en/aws/appsync/index.md
- content/en/localstack/configuration.md
Relates to changes in: https://github.com/localstack/localstack-ext/pull/297
> Add GRAPHQL_ENDPOINT_STRATEGY

- content/en/aws/sqs/index.md
- content/en/localstack/configuration.md
docs for https://github.com/localstack/localstack/pull/6140, and config reference entry for SQS_ENDPOINT_STRATEGY
> add SQS configuration variables

- content/en/tools/lambda-tools/hot-swapping/index.md
Small update in docs, covering the use case of expanding module search path (`sys.path`) for virtualenv Lambda hot swapping.
This topic came up in one of the community Slack channels - while the watchman script approach is useful, it comes with a bit of overhead (watching the fs, copying the libs into a folder). The approach with expanding module search path is an alternative/orthogonal approach - appears a bit more lightweight (although it requires a modification to the handler code itself).
Over time, we can expand the docs to showcase how virtualenv libs can be mounted as a Lambda _layer_, which then becomes available to the Lambda handler (once fully implemented).
> Add docs for expanding module search path for virtualenv Lambda hot swapping

- content/en/aws/rds/index.md
Update docs and default password for RDS MSSQL DBs.
> Update docs and default password for RDS MSSQL DBs

- content/en/localstack/arm64-support/index.md
> Update command to check architecture

- content/en/aws/elastic-kubernetes-service/index.md
See https://github.com/localstack/localstack-ext/pull/730
Relevant part in: https://localstack-docs-preview-pr-181.surge.sh/aws/elastic-kubernetes-service/#mounting-directories-from-host-to-pod
> Add documentation for EKS volume mounting

- content/en/aws/rds/index.md
This is a draft to update the documentation about `rds-data` and the examples to follow up on recent updates.
> update doc about rds-data

- content/en/aws/iam/index.md
This adds documentation regarding IAM engine features / changes, namely:
* Default root user - documents that invalid access keys lead to root privileges
* Explainable IAM - demonstrate log entries explaining missing permissions for requests
> Update documentation for new IAM engine features in v1

- content/en/localstack/configuration.md
- content/en/localstack/filesystem.md
Did an iteration over the filesystem section and cleaned up some of the configuration parameters.
> update filesystem description and configuration

- content/en/tools/cloud-pods/pods-cli/index.md
minor nit: rename Synopsys->Synopsis (I think that's the correct spelling if I'm not mistaken).
> minor: rename Synopsys->Synopsis

- content/en/developer-guide/setup.md
- content/en/get-started/_index.md
- content/en/localstack/configuration.md
Fixes https://github.com/localstack/docs/issues/211
> move host mode docs to developer guide

- content/en/integrations/aws-cdk/index.md
- content/en/tools/lambda-tools/hot-swapping/index.md
Adds additional information for Lambda hot reloading with CDK which came up while developing https://github.com/silv-io/office-scoreboard
> Update CDK hot reloading docs

- content/en/aws/sqs/index.md
adds a limitation section to the SQS docs and adds a specific limitation related to https://github.com/localstack/localstack/issues/5225
> add limitations section to SQS

- content/en/aws/sqs/index.md
- content/en/localstack/configuration.md
Adds docs for https://github.com/localstack/localstack/pull/6710
> add docs for sqs purge queue behavior

- content/en/localstack/configuration.md
adds docs for https://github.com/localstack/localstack/pull/6730
> add DYNAMODB_IN_MEMORY to configuration.md

- content/en/localstack/filesystem.md
- content/en/localstack/init-hooks.md
This PR adds documentation for init hooks introduced in https://github.com/localstack/localstack/pull/6716
also added @dominikschubert as reviewer to check whether the docs clarify all the questions you had.
> add documentation for new init hook system

- content/en/tools/cloud-pods/pods-cli/index.md
- Adds description of cli status command
- (Trailing spaces)
> [CloudPods] cli status command

- content/en/get-started/_index.md
Fixes https://github.com/localstack/docs/issues/186
> DOC: Add more context to LocalStack getting started

- content/en/ci/gitlab-ci/index.md
Fixes https://github.com/localstack/docs/issues/254
> docs: add gitlab ci to list of supported services

- content/en/get-started/_index.md
Adding instructions to install localstack specific version.
> Updating documentation to specify version

- content/en/aws/sns/index.md
This PR adds documentation about an SNS feature recently introduced with https://github.com/localstack/localstack/pull/6661
> add documentation about SNS internal endpoints

- content/en/aws/kinesis-firehose/index.md
Hello, seems that in this snippet the stream name doesn't match with the rest
> Docs: Fix stream name in firehose example

- content/en/get-started/_index.md
Updating docker-compose and docker instructions to specify docker image version
> Updating docker-compose and docker instructions

- content/en/aws/mq/index.md
This PR adds a first version of MQ docs.
> Add MQ docs

- content/en/aws/apigatewayv2/index.md
> AWS ApiGateway Custom ID via tags 

- content/en/aws/apigatewayv2/index.md
> Update AWS Custom ID example

- content/en/aws/lambda/index.md
> Update Lambda docs

- content/en/developer-guide/Concepts/index.md
This PR documents the changes introduced by the new [Packages/Installer Hierarchy](https://github.com/localstack/localstack/pull/6783) and [lpm refactoring](https://github.com/localstack/localstack/pull/7063)
> lpm doc change according to the new installer hierarchy

- content/en/aws/elastic-kubernetes-service/index.md
Add docs for EKS HTTPS ingress with SSL certificate.
> Add docs for EKS HTTPS ingress with SSL certificate

- content/en/user-guide/aws/glacier/index.md
This PR:
- Adds starting information to AWS Glacier 
- Add a simple getting started guide
- Link to the configuration page for supported APIs
Preview: https://localstack-docs-preview-pr-343.surge.sh/user-guide/aws/glacier/
> add docs for aws glacier

- assets/scss/_styles_project.scss
This PR makes hyperlinks more prominent and easier to navigate.
> More prominent hyperlinks

- content/en/user-guide/tools/cloud-pods/pods-cli/index.md
This PR updates the CLI reference for Cloud Pods that's going out with 1.3.
> Update CLI reference for Pods

- content/en/user-guide/aws/lambda/index.md
- content/en/user-guide/aws/s3/index.md
Fixes https://github.com/localstack/docs/issues/379
> Add info about `PROVIDER_OVERRIDE_*` flag

- content/en/references/coverage.md
- content/en/user-guide/aws/feature-coverage.md
Fixes https://github.com/localstack/docs/issues/338
> Add AWS service names in the docs feature coverage

- content/en/user-guide/aws/transcribe/index.md
https://github.com/localstack/localstack/pull/6852
> Update transcribe docs

- content/en/references/configuration.md
See https://github.com/localstack/localstack/pull/7346
> Add new configuration from 0.3.0 Kinesis Mock

- content/en/user-guide/aws/elastic-compute-cloud/index.md
Add contents for security group ingress ports, user data and key pairs
> Update EC2 docs

- content/en/user-guide/web-application/accounts/index.md
- content/en/user-guide/web-application/teams/index.md
Based on @lukqw comments here: https://github.com/localstack/docs/pull/414#pullrequestreview-1230550962
> fix web app docs nits

- content/en/user-guide/aws/apigatewayv2/index.md
Section on how to call custom domain mappings with LocalStack.
>  API Gateway REST APIs and v2 call custom domains

- content/en/user-guide/aws/rds/index.md
Add docs for new MySQL support, and some details to other engines.
**Do not merge yet :)**
> add MySQL support for RDS + improve docs

- content/en/getting-started/faq.md
> document docker network IP forwarding

- content/en/references/persistence-mechanism.md
- content/en/user-guide/tools/cloud-pods/_index.md
> Add warning note about state incompatibility

- content/en/user-guide/tools/lambda-tools/debugging/index.md
Publishing the debugging port from a lambda container to the host is only necessary for VS Code debugging, not for Pycharm Professional. This was not properly represented and lead to confusion for the users.
Also, the limitations only applied to the VS Code version, as they are limitations of the port publishing.
* Move some paragraphs / paragraph heading levels to make the needed configurations clearer.
* Changed `__local__` bucket key to `hot-reload`.
> Clarify port publishing needs for debugging purposes

- content/en/user-guide/aws/ses/index.md
Following up on https://github.com/localstack/localstack/pull/7816
> SES: Add service endpoint details

- content/en/user-guide/integrations/sdks/dotnet/index.md
Adding more informations about setting the S3 endpoint for .NET, and information about how to set `ForcePathStyle`.
> wip: add S3 note for .NET SDK

- content/en/references/configuration.md
Related to https://github.com/localstack/localstack/pull/7997
> Update config vars

- content/en/getting-started/api-key.md
- content/en/getting-started/installation.md
- content/en/references/configuration.md
This PR documents the new pro activation procedure.
> update docs on v2 pro activation procedure

- content/en/getting-started/quickstart.md
closes https://github.com/localstack/docs/issues/488
> add mention of make to quickstart guide

- content/en/user-guide/aws/iot/index.md
> Revert "IoT: Add lifecycle events"

- content/en/user-guide/tools/lambda-tools/debugging/index.md
found and fixed a small typo + fix phrasing
> Fix lambda debugger typo

- content/en/user-guide/aws/iot/index.md
Follow up on https://github.com/localstack/docs/pull/557
To be merged with v2.1 release
> IoT: Add lifecycle events

- content/en/user-guide/aws/opensearch/index.md
Added in https://github.com/localstack/localstack/pull/8167
> Support for OpenSearch 2.5

- content/en/references/init-hooks.md
> fix a couple of typos in init-hooks.md

- content/en/references/configuration.md
- content/en/user-guide/aws/sqs/index.md
> add docs to disable cloudwatch metrics for sqs

- content/en/references/cross-account-access.md
- content/en/user-guide/integrations/aws-cli/index.md
Depends on:
- https://github.com/localstack/localstack/pull/8339
- https://github.com/localstack/localstack/pull/8395
[Jump to content](https://localstack-docs-preview-pr-644.surge.sh/references/cross-account-access/)
> Update cross-account docs

- content/en/user-guide/aws/elastic-compute-cloud/index.md
See https://github.com/localstack/localstack-ext/pull/1746
> Add deprecation note about LocalStack daemon

- content/en/references/persistence-mechanism.md
Add info about the snapshot endpoints that do a complete save/load operation.
> improving docs for persistence endpoints

- content/en/user-guide/aws/rds/index.md
preparing some notes about limitations of global cluster/global databases for RDS
> add docs for global database on rds

- content/en/user-guide/aws/transfer/index.md
Changes the description of how we handle returning the port of the created transfer server in accordance to the mentioned changes.
> change description of the port handling

- content/en/applications/search-application-with-lambda-kinesis-firehose-elasticsearch-s3/index.md
- content/en/applications/serverless-rds-proxy-with-api-gateway-lambda-and-aurora-rds/index.md
- data/developerhub/applications.json
* add proxy-demo app /cc @sannya-singal 
* fix information for serverless image resizer (it's requiring pro version)
* generated the empty content pages for developer samples
>  add proxy-demo app

- content/en/getting-started/api-key.md
> Update api-key.md - Fix the PowerShell syntax

- content/en/getting-started/faq.md
Add to FAQ - how to resolve UTF-8 issue with LocalStack CLI under Windows
> Add to FAQ - how to resolve UTF-8 issue with LocalStack CLI under Windows

- content/en/references/init-hooks.md
Resolve : https://github.com/localstack/docs/issues/735
> Remove legacy init scripts note - init-hooks.md

- content/en/references/localstack-extensions.md
Fixed some typos in the localstack-extensions.md file.
Ticket #740
> Fixed some typos

- content/en/user-guide/aws/sqs/index.md
This PR addresses #627. Generally this is something that users have been struggling with, and I think this initial iteration should clarify most of the questions people have.
> add section to sqs on accessing queues from lambdas

- content/en/user-guide/aws/lambda/index.md
The documentation did not have example of invoking Lambda directly. I added it.
Closes #745
> Added direct Lambda invoke documentation

- content/en/references/persistence-mechanism.md
Make it visible that persistence is part of LocalStack Pro.
> Bold change of the persistence text

- content/en/user-guide/aws/kms/index.md
Add note about custom IDs for KMS keys to our docs. Documentation for this PR: https://github.com/localstack/localstack/pull/8870
> Add note about custom IDs for KMS keys

- content/en/user-guide/aws/lambda/index.md
Added tab panes with commands for AWS CLI v1 and AWS CLI v2.
> updated the lambda invoke section

- content/en/user-guide/aws/rds/index.md
* remove default password notes
* clarify creation of cluster + instances
* move note about adaption of secret-arn above the code sample
> enhance RDS docs

- content/en/user-guide/aws/glacier/index.md
Enhance the Glacier docs to be in-line with the others services.
page: https://localstack-docs-preview-pr-816.surge.sh/user-guide/aws/glacier/
> enhance Glacier documentation

- content/en/user-guide/aws/mq/index.md
- content/en/user-guide/aws/transcribe/index.md
This PR reformats the docs pages for the services mq and transcribe. Hope I got it right :crossed_fingers:
> reformat mq and transcribe

- content/en/user-guide/tools/cloud-pods/remotes/index.md
Some initial documentation for the Cloud Pods remotes (cc @cabeaulac)
> pod remotes

- content/en/references/configuration.md
See https://github.com/localstack/localstack-ext/pull/2144
> drop persist all variable in docs

- content/en/references/configuration.md
- content/en/user-guide/aws/rds/index.md
Add docs about configuration of `RDS_CLUSTER_ENDPOINT_HOST_ONLY`.
See original issue: https://github.com/localstack/localstack/issues/9235
> add docs for RDS_CLUSTER_ENDPOINT_HOST_ONLY configuration

- content/en/references/localstack-extensions.md
Add links to GitHub repo and describe development mode for LocalStack Extensions (based on external feedback).
Content partly copied from the Extensions repo: https://github.com/localstack/localstack-extensions
Based on the latest updates from https://github.com/localstack/localstack-extensions/pull/29
It might be a bit confusing to have two `LocalStack Extensions` pages:
* References: https://docs.localstack.cloud/references/localstack-extensions/
* Tools list (badly outdated): https://docs.localstack.cloud/user-guide/tools/localstack-extensions/
At least, we should clarify the intent and cross-link accordingly. I guess the idea was to have the API and conceptual part covered under references and the actual extensions in the tools list 🤔  @HarshCasper
> Add links and describe dev mod for extensions

- content/en/user-guide/aws/glue/index.md
Add docs for querying Delta Lake tables in Glue PySpark jobs.
> Add docs for querying Delta Lake tables in Glue PySpark jobs

- content/en/user-guide/integrations/cloud-custodian/index.md
Preview link: https://localstack-docs-preview-pr-865.surge.sh/user-guide/integrations/cloud-custodian/
> docs for cloud custodian

- content/en/user-guide/aws/sqs/index.md
Adds docs for https://github.com/localstack/localstack/pull/9357
> add new sqs developer endpoint feature

- content/en/user-guide/aws/qldb/index.md
- general info about the service
- creating ledger via aws cli
- creating a table via qldb shell
- querying a table 
- modifying documents in a ledger
- viewing the revision history of a document
- update/delete ledger
> enhance QLDB docs

- content/en/user-guide/aws/kms/index.md
Related issue: [#7311](https://github.com/localstack/localstack/issues/7311)
> add unsupported key spec in kms doc

- content/en/references/configuration.md
Adds config details for new feature of strict services loading and the related env `SERVICES`
> add details for SERVICES configuration

- config.toml
- content/en/overview/_index.html
Version 3.0.0 is about to be released.
This PR performs the last changes for 3.0.
- Updates the LocalStack version (used in links to the CLI or in some code sections) to 3.0.0.
- Updates the banner to link to a newly published discuss post describing / announcing the release.
> Update versions to 3.0, update banner

- content/en/getting-started/api-key.md
- content/en/user-guide/web-application/ci-keys/index.md
- content/en/user-guide/web-application/users-licences/index.md
adding clarification for ci keys
> adding some callouts about ci keys

- content/en/getting-started/installation.md
Removed the Cockpit links to LocalStack Desktop.
> Change Cockpit to LocalStack Desktop

- content/en/references/configuration.md
- content/en/user-guide/aws/docdb/index.md
Improving the sample, and removing the `LOCALSTACK_HOST` usage.
> improve documentdb docs

- config.toml
We just released version 3.0.2, this PR changes the version / links to the new version.
> update version to 3.0.2

- content/en/references/configuration.md
- content/en/user-guide/cloud-pods/auto-load/index.md
Long overdue update to the docs.
> pod auto-load feature

- content/en/user-guide/tools/dns-server/_index.md
quickfix for the wrong path of the DNS server redirect
> Fix dns server redirect

- content/en/user-guide/aws/amplify/index.md
Fixes https://github.com/localstack/docs/issues/855
> deprecate amplifylocal and amplify js library

- content/en/getting-started/installation.md
- content/en/references/configuration.md
- content/en/references/external-ports.md
- content/en/references/init-hooks.md
- content/en/references/network-troubleshooting/endpoint-url/_index.md
- content/en/references/persistence-mechanism.md
- content/en/tutorials/java-notification-app/index.md
- content/en/user-guide/aws/elasticsearch/index.md
- content/en/user-guide/aws/opensearch/index.md
- content/en/user-guide/cloud-pods/auto-load/index.md
- content/en/user-guide/extensions/managing-extensions/index.md
- content/en/user-guide/integrations/kafka/docker-compose.yml
Synchronize changes with our new recommended `docker-compose.yml` in https://github.com/localstack/localstack/pull/9822
* Synchronize with recommended `docker-compose.yml` from https://github.com/localstack/localstack/pull/9822
* Add `DOCKER_HOST` to configuration under misc now that we remove it from the docker-compose
* Add `LOCALSTACK_API_KEY` as deprecated configuration variable and add links
> Refine docker compose yml

- content/en/getting-started/auth-token.md
Add a Windows command to invoke the information endpoint.
> Add a Windows command to invoke the information endpoint.

- content/en/user-guide/extensions/managing-extensions/index.md
> Update extension installation with LOCALSTACK_VOLUME_DIR instructions

- content/en/user-guide/aws/transcribe/index.md
Reverts localstack/docs#961
Fixed by https://github.com/localstack/localstack/pull/9898
> Transcribe: Remove audio-files-only limitation

- content/en/user-guide/aws/managed-blockchain/index.md
Merge when `managedblockchain` is available in the `localstack/localstack-pro:latest` image
> add managed blockchain docs

- content/en/user-guide/integrations/terraform/index.md
Fixes https://github.com/localstack/localstack/issues/5705
> add terraform target module docs

- content/en/user-guide/aws/lambda/index.md
Fixes https://github.com/localstack/docs/issues/224
> document supported ESMs for Lambda

- content/en/getting-started/auth-token/index.md
Add CI key configuration instructions. It's not so straightforward for everybody.
> Add CI key configuration instructions

- content/en/user-guide/aws/docdb/index.md
Adding missing "\" to the create DB instance command.
> updated create db instance command.

- content/en/references/configuration.md
- content/en/user-guide/aws/dynamodb/index.md
Adding docs for the feature implemented in https://github.com/localstack/localstack/pull/10041.
> ddb support for TTL

- content/en/user-guide/aws/cloudformation/index.md
Slightly rephrases the sentence on preferring stack recreations (instead of updating).
/cc @cabeaulac
> fix stack re-creation tip

- content/en/user-guide/web-application/single-sign-on/_index.md
Rephrasing parts of our docs around self assigning licenses to make them more clear
> rephrase wording in section about self assigning licenses

- data/developerhub/applications.json
super small correction for better display
> correct filter option from csharp to .NET

- config.toml
> Bump localstack version for latest release

- content/en/getting-started/faq.md
There is some misconception on the semantics of our Docker tags (e.g. "what means `latest`"?).
This PR adds a section to the FAQ section on the docs describing the semantics of the different tags.
Happy for any feedback!
- First commit contains some cleanup to have every sentence in the FAQ section in its own line in the markdown file (according to our best practices, which helps a lot with reviews / diffs).
- The second commit adds a section which explains the semantics of the different tags.
> add FAQ on Docker image tags

- data/developerhub/applications.json
Adds the [Lambda SAM Authorizer](https://github.com/localstack-samples/lambda-sam-authorizer/tree/main) sample to the Developer Hub.
> add lambda authorize sample to developer hub

- content/en/user-guide/state-management/cloud-pods/index.md
Add note that pods S3 remote requires CLI install via pip.
/cc @giograno @alexrashed
> Add note that pods S3 remote requires CLI install via pip

- content/en/getting-started/help-and-support.md
Update the sentence:
"If you have discovered outdated documentation, please on our documentation."
"If you have encountered outdated documentation, please report it on our [documentation GitHub page](https://github.com/localstack/docs)."
> Update help-and-support GH section

- content/en/user-guide/state-management/cloud-pods/index.md
This PR adds a small note on pod limitations, most notably version compatibility and not supporting all services.
> note on pods limitation

- content/en/user-guide/state-management/pods-cli/index.md
Remove broken code annotations in the list section. Partial fix of https://github.com/localstack/docs/issues/704
> Fix bug #704

- content/en/user-guide/aws/stepfunctions/index.md
Updates the StepFunctions optimised service integrations to include ECS, which was recently merged
> [SFN] Update Optimised Services Support Table

- content/en/user-guide/integrations/testcontainers/index.md
NodeJS module are now available
> Add nodejs to testcontainer documentation

- content/en/user-guide/web-application/accounts/index.md
This PR updates two broken links on the accounts page in our docs.
> fix accounts links

- content/en/contributing/terraform-tests.md
Fixed a broken link for terraform test suite workflow
> fix: terraform suite workflow borken link

- content/en/user-guide/integrations/pulumi/index.md
The provided configuration didn't work, so i replaced it with the configuration generated by the pulumi-local tool.
> Update pulumi configuration

- content/en/user-guide/ci/_index.md
> Broken link snytax

- content/en/user-guide/integrations/aws-cdk/index.md
Fixes https://github.com/localstack/docs/issues/998
> add a note about updating cdk stacks

- content/en/references/cross-account-access.md
This PR introduces documentation for ARN-based retrieval in SecretsManager for suppored APIs.
- https://github.com/localstack/localstack/pull/10501
- https://github.com/localstack/localstack/pull/10457
> added list of apis support arn  based reterival

- content/en/user-guide/aws/cloudformation/index.md
Related PR: https://github.com/localstack/localstack/pull/10670
> add support of cfn resource AWS::Events::ApiDestination

- content/en/references/configuration.md
Add the CFn environment variable options to the Configuration section.
- CFN_VERBOSE_ERRORS added
- CFN_PER_RESOURCE_TIMEOUT added
> Add CFn env options to the Config section

- content/en/getting-started/auth-token/index.md
> remove deep link into app pricing page

- content/en/user-guide/aws/glue/index.md
Fix https://github.com/localstack/docs/issues/1230
> add a simple glue script to the docs

- content/en/references/iam-coverage.md
This PR documents:
- Add supported services
- Add inter service enforcement 
- Add supported policy types and features
> add IAM coverage map

- content/en/user-guide/aws/cloudformation/index.md
This PR documents:
- New resource provider for AWS::EFS::AccessPoint resource provider
- New resource provider for AWS::EFS:MountTarget resource provider
- New resource provider for AWS::Cloudfront::ResponseHeadersPolicy
> document new cfn resources

- content/en/user-guide/aws/sns/index.md
This PR updates the documentation following 2 LocalStack PRs: https://github.com/localstack/localstack/pull/9336 and https://github.com/localstack/localstack/pull/8667, for internal access to SMS messages and Subscription Tokens.
It updates and regroup the documentation around `Developer Endpoints`, and updates the commands there so they can be copied over without copying the result of the command. 
Preview at https://localstack-docs-preview-pr-1263.surge.sh/user-guide/aws/sns/#developer-endpoints
_fixes #1246_
> update documentation on SNS internal dev endpoint

- content/en/user-guide/integrations/sdks/_index.md
Fixes https://github.com/localstack/docs/issues/249
> add some basic intro on connecting sdks to localstack

- content/en/user-guide/aws/athena/index.md
Fixes https://github.com/localstack/docs/issues/606
This PR documents:
- awswrangler
- PyAthena
I was not able to get a satisfactory example working for sqlalchemy, hence dropped it for now.
> add docs on awswrangler and pyathena

- content/en/user-guide/aws/stepfunctions/index.md
Updates the AWS StepFunctions's optimised service integration table to include Glue.
> [SFN] Update Optimised Support Table to Include Glue

- content/en/user-guide/aws/cloudformation/index.md
This PR documents support for:
- Resource provider for AWS::SageMaker::Model
- Resource provider for AWS::SageMaker::Endpoint
- Resource provider for AWS::SageMaker::EndpointConfig
> document sagemaker cfn resources

- content/en/getting-started/installation.md
Based on https://github.com/localstack/localstack/issues/10905
> add troubleshooting section on localstack cli not starting

- data/persistence/coverage.json
Following up from https://github.com/localstack/localstack/issues/9974.
Tired to come up with a better description (the old one was kinda bad). I did not manage to implement a link in an automatic fashion from the Notion table unfortunately.
👀  => https://localstack-docs-preview-pr-1301.surge.sh/user-guide/state-management/support/
> Better description of Lambda limitation for hot-reloading

- content/en/user-guide/aws/kms/index.md
- https://github.com/localstack/localstack/issues/8910
- https://github.com/localstack/localstack/pull/10379
Was searching for a way to do this in Localstack v3 and foudn the ticket and PRs above, but key material was not documented.
> Add Documentation on _custom_key_material_ KMS Key Tag

- content/en/user-guide/ci/circle-ci/index.md
New orb is released, so we'd like to highlight the available commands in it.
- update snippet library for CircleCI
> New circleci snippets based on new orb

- content/en/user-guide/aws/ec2/index.md
> [!CAUTION]
This PR clarifies the possibility of using AWS AMIs or customising them on LocalStack.
It also elaborates stuff about user data shell script execution.
> EC2: Add further docs on AMIs and instances

- content/en/user-guide/aws/rds/index.md
Add docs around RDS Postgres extension functions. This information has recently been requested by a user in the Community Slack channel. /cc @komarkovich
> Add docs around RDS Postgres extension functions

- content/en/user-guide/state-management/cloud-pods/index.md
Adding docs for the recently merged cloud pods end-to-end feature.
> docs for pods encryptions

- content/en/user-guide/aws/lambda/index.md
This PR documents the changes made in [this localstack-core PR.](https://github.com/localstack/localstack/pull/11103)
> Add docs for ``_custom_id_`` for lambda function URLs

- content/en/user-guide/aws/cloudwatch/index.md
Change note about the default provider.
> adapt information about default cloudwatch provider

- content/en/user-guide/tools/transparent-endpoint-injection/index.md
Updated sentence for readability
> Nit verbiage add index.md

- content/en/references/internal-endpoints.md
- content/en/tutorials/ecs-ecr-container-app/index.md
- content/en/tutorials/elb-load-balancing/index.md
- content/en/tutorials/java-notification-app/index.md
- content/en/user-guide/aws/apigateway/index.md
- content/en/user-guide/aws/firehose/index.md
- content/en/user-guide/aws/lambda/index.md
- content/en/user-guide/aws/s3/index.md
- content/en/user-guide/aws/sns/index.md
- content/en/user-guide/aws/sqs/index.md
This PR fixes capitalisation of **cURL** to **curl**, and updates links wherever relevant.
> Fix capitalisation for curl

- content/en/user-guide/aws/ec2/index.md
> [!CAUTION]
This PR updates EC2 docs to add:
- Libvirt VMM support for user data scripts
- a troubleshooting tip when configuring libvirt
> EC2: Update Libvirt VMM docs

- content/en/references/init-hooks.md
Adding a question about the LF and CRLF modes, which can cause issues when loading a file in a Linux container if the file was created in a Windows environment.
> Update init hooks troubleshooting section with question about LF and CRLF mode

- content/en/user-guide/integrations/eksctl/index.md
For now, to ensure compatibility with the latest versions of `eksctl`, here is an update to the command to set the endpoints. This resolves the connectivity issues.
> update the eksctl command

- content/en/user-guide/lambda-tools/debugging/index.md
Introduces docs for the Lambda Debug Mode preview feature.
> [Lambda DevX] Introducing Lambda Debug Mode

- content/en/user-guide/aws/elb/index.md
It looks like there is a typo in the LB docs.
> Update index.md typo in Listener

- content/en/getting-started/faq.md
- content/en/getting-started/help-and-support/index.md
- content/en/overview/_index.html
Added on home page, help page and FAQ.
> Add links to status page

- content/en/getting-started/faq.md
I updated the doc to make it more clear on how to solve the issue or use a workaround in case of running older version of LS
> Update FAQ section for SSL issue resolving instructions

- content/en/user-guide/aws/iot/index.md
> [!NOTE]
Updates the awsiotsdk code sample to use proper AWS credentials.
> IoT: Update awsiotsdk WSS code snippet

- content/en/user-guide/aws/mwaa/index.md
> [!NOTE]
Introduces support for Airflow 2.9.2
https://aws.amazon.com/about-aws/whats-new/2024/07/amazon-mwaa-apache-airflow-version-2-9/
> MWAA: Add support for Airflow 2.9.2

- content/en/user-guide/aws/events/index.md
doc update for https://github.com/localstack/localstack/pull/11544
> Add API gateway as new supported target

- content/en/user-guide/aws/lambda/index.md
Update status for 3.8 release
Related to https://github.com/localstack/localstack/pull/11625
> Update ESM v2 status

- content/en/user-guide/aws/pinpoint/index.md
> [!NOTE]
This PR adds documentation for OTP validation operations in Pinpoint.
> Pinpoint: OTP operations

- content/en/user-guide/aws/mwaa/index.md
> [!NOTE]
MWAA now supports Airflow 2.10.1
> MWAA: Add support for Airflow 2.10.1

- layouts/shortcodes/github.html
Resolving an error when running locally, see [relevant discussion](https://localstack-cloud.slack.com/archives/C02FZH6UB2A/p1730286805383739) (internal). Cc @viren-nadkarni 
Not sure about the code changes, but running locally works OK with this.
> Update layout shortcodes

- content/en/references/configuration.md
This environment variable will be added to the list of environment variables that the CLI passes through.
Companion PR: https://github.com/localstack/localstack-ext/pull/3829
> CLI Config: ADD MSSQL_ACCEPT_EULA docs for RDS

- content/en/user-guide/aws/kinesisanalyticsv2/index.md
> Revert "Managed Flink: Tagging support and CloudWatch Logs integration"

- content/en/user-guide/aws/pinpoint/index.md
Fix the typo in "SentOTPMessage" to "SendOTPMessage".
> docs: Fix Typo

- content/en/getting-started/help-and-support/index.md
In reference to this [PR](https://github.com/localstack/docs/pull/1515#issuecomment-2405080228) I removed the callout note and moved the language support sentence to the Support resources section.
> Lenguage coverage modification

- content/en/getting-started/quickstart/index.md
- content/en/user-guide/aws/dms/index.md
Add support for PostgreSQL as a source in DMS.
> DMS: add support for PostgreSQL source

- data/developerhub/applications.json
Add DMS PostgreSQL source and Kinesis target use case sample to developer hub
> dms: add postgres to kinesis use case sample to dev hub

- content/en/user-guide/aws/transcribe/index.md
This PR updates the list of supported languages and dialects. Also clarified is limitations around speaker diarization, confidence levels, etc.
See https://github.com/localstack/localstack/pull/12336
> Transcribe: New language models

- content/en/user-guide/aws/lambda/index.md
- Change SQS Standard queue `BatchSize` coverage from 🟡 to 🟢 
- Change SQS/Kinesis/DynamoDB Streams `MaximumBatchingWindowInSeconds` coverage from 🟠 to 🟢
> [ESM] Sync coverage table with improved batching support

- content/en/getting-started/help-and-support/index.md
Fixes https://github.com/localstack/docs/issues/1638
> remove the reference to the discuss forum

- content/en/user-guide/aws/elb/index.md
Simple change to specify the support of fixed-response action types
> Change message about supported action types of ELB

- content/en/user-guide/aws/scheduler/index.md
See https://github.com/localstack/localstack/issues/11263#issuecomment-2259090633
> document limitations with the scheduler service

- content/en/references/licensing.md
> Fix link in the new licensing.md
