content/en/integrations/terraform/index.md
Terraform does not have a deploy command, so it will not work. It has apply command which provisions the resources specified in the config file. Changing this to apply make this work.
=> change invalid terraform command deploy to apply

content/en/localstack/configuration.md, content/en/localstack/lambda-executors.md
This PR adds docs and information about configuration variables introduced with https://github.com/localstack/localstack/pull/5088.
It also explains the difference between the `exec` docker reuse mode and the stay-open mode and mentiones limitations of the latter.
=> Add docs for stay open mode

content/en/aws/timestream/index.md
This PR documents the following Timestream DB functions: 
- `ago(..)`
- `bin(..)`
- `parse_duration(..)`
- `from_iso8601_date(..)`
- `from_iso8601_timestamp(..)`
=> DOCS: Add docs about Timestream DB functions

content/en/aws/multi-region-support/index.md
This PR removes the multi-region support docs, which is supported across LocalStack now (Community & Pro both). This PR is with respect to https://github.com/localstack/localstack/issues/5147
=> DOCS: Remove multi-region support docs

content/en/localstack/configuration.md
This PR:
- Adds info about `ENABLE_CONFIG_UPDATES`
- Adds info about `MOCK_UNIMPLEMENTED`
- Adds info about `LOCALSTACK_HOSTNAME`
=> DOCS: Add missing configurations

content/en/get-started/_index.md, content/en/localstack/configuration.md
Currently, it seems not clear to users when to set this.
Until we can get rid of the necessity of this variable, it should be mentioned more prominently.
Addresses https://github.com/localstack/localstack/issues/5130 https://github.com/localstack/localstack/issues/5140
=> Add hint to get-started about LAMBDA_DOCKER_NETWORK

content/en/aws/elasticsearch/index.md, content/en/aws/kinesis-firehose/index.md
This PR adds a sample how to manually (using aws CLI) create an integration using AWS Firehose to deliver Kinesis stream data to ElasticSearch and S3 as full backup.
Example was created on request for a customer, so the little additional work turning it into a docs article seemed worth it.
=> Add example for Firehose integration with ES, S3 and Kinesis

content/en/aws/cloudformation/index.md, content/en/aws/elasticache/index.md, content/en/localstack/podman/index.md
This PR:
- Documents `create-replication-group` API for ElastiCache
- Reverts the Authorizers Pro status
- Fixes typos across Podman-specific docs
- Documenta support for `AWS::QLDB::Ledger`
=> Documentation updates across LocalStack

content/en/localstack/configuration.md
When adding the docs for OpenSearch with https://github.com/localstack/docs/pull/108/, we did not specifically highlight the deprecation of the elasticsearch specific environment variables.
This PR tries to make this a bit more explicit and adds links to the configuration variables in favor.
=> add deprecation warning and description for elasticsearch / opensearch

content/en/localstack/configuration.md
The default location for `INIT_SCRIPTS_PATH` incorrectly contains a trailing dot.
=> Fix `INIT_SCRIPTS_PATH` default location

content/en/localstack/configuration.md
This PR adds a short section for AWS Batch in the service specific configuration section which describes the config variable `BATCH_DOCKER_FLAGS`.
=> add docs for BATCH_DOCKER_FLAGS

content/en/localstack/lambda-executors.md
highlights the need to bind mount the docker socket when running localstack container and lambda executors in docker mode
Practising learnings from today's workshop.
=> add bind mount example

.github/workflows/github-pages.yml, .github/workflows/preview-build.yml, .github/workflows/preview-deploy.yml, .github/workflows/preview-start.yml
This PR:
- Adds a custom workflow to deploy docs using `npx` and `surge`
- Adds an action to install, build and store the build as an artifact
- Adds a workflow step to put up a GitHub comment on respective PRs after deploying
=> CI: Enable PR previews for docs

content/en/get-started/_index.md
This PR adds documentation regarding `network_mode: bridge` (which disables docker container name resolution, see https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge)
Also adds documentation regarding upgrade difficulties for LS CLI, see:
Fixing https://github.com/localstack/localstack/issues/5649
=> Update getting started guide with information regarding docker networks and upgrade difficulties

content/en/aws/elastic-kubernetes-service/index.md, content/en/get-started/_index.md
Due to recent interest, I created a small sample to demonstrate the integration between EKS and ECR and its pitfalls (mainly the possibility of failure to resolve `localhost.localstack.cloud`).
It is a small example, with the necessary explanation at the beginning, with a small sample to demonstrate (nothing special, just creating a pod up to the point where the image is pulled) afterwards, using awscli. With the correct configuration of `EXTERNAL_HOSTNAME`, any IaC tool should work as well though.
=> Add tutorial on ECR EKS integration

content/en/developer-guide/setup.md
These instructions were removed from the localstack `README` file.
=> development environment setup instructions

content/en/get-started/_index.md, content/en/localstack/configuration.md
Port 4571 is not used by any default configuration (only legacy elasticsearch), ports 4510-4559 are however used more frequently.
I also removed the hint to the "SERVICES" variable, as we see a lot of misuse in support. Up to discussion!
Main target of this PR is the addition of documentation regarding the environment variable introduced in https://github.com/localstack/localstack/pull/6000 .
This variable disables "orderly" shutdown of LocalStack by preventing passing signals from docker-entrypoint.sh to supervisor.
=> Document DISABLE_TERM_HANDLER, update docker run command in getting-started

content/en/aws/cognito/index.md, content/en/aws/elastic-compute-cloud/index.md, content/en/aws/ses/index.md, content/en/localstack/configuration.md
This PR adds missing environment config options for Simple Email Service.
=> Document SES configuration options

content/en/aws/glue/index.md
This PR adds a short section on the Glue Schema Registry (and links to the sample in the [localstack-pro-samples](https://github.com/localstack/localstack-pro-samples/tree/master/glue-msk-schema-registry) repo).
=> add Glue Schema Registry (short example, link to the pro-sample)

content/en/localstack/configuration.md
This PR adds documentation regarding configuration options for the bigdata container (and therefore the service dependent on it), namely:
* `BIGDATA_DOCKER_NETWORK` which allows the bigdata container to be connected to a specific network
* `BIGDATA_DOCKER_FLAGS` which allows to configure additional flags (volume mounts, host file modifications,...) to be added to the bigdata container.
Also, per customer feedback, I clarified the `LAMBDA_REMOVE_CONTAINERS` option, as it was unclear in which lambda executors it had any effect.
=> Add docs about Bigdata configuration options

content/en/localstack/configuration.md
Fixes https://github.com/localstack/docs/issues/98
Preview doc: https://localstack-docs-preview-pr-140.surge.sh/localstack/configuration/#profiles
=> DOCS: Add docs about configuration profiles in LocalStack

content/en/developer-guide/setup.md
https://github.com/localstack/localstack/pull/6050 has been merged, it appears that Python 3.10 or higher is now required.
I tried to `make install` with Python 3.9, and the following notation gave me a TypeError.
https://github.com/localstack/localstack/blob/master/localstack/testing/aws/cloudformation_utils.py#L9
ref: https://peps.python.org/pep-0604/
=> update requirements python version

content/en/integrations/sdks/dotnet/index.md
Currently, we have no documentation on how to create a client (and set its region) for the .NET SDK.
This can lead to problems when people might use RegionEndpoint to set the region (which does not work against LS).
This adds a small page (inspired/copied from PHP), about how to set regions and create clients correctly in the .NET AWS SDK.
=> Add docs for .net sdk

content/en/localstack/configuration.md, content/en/tools/multi-account-setups/index.md
This change moves the Multi-accounts documentation from AWS Services section to Tools section.
There is an alias added so the old link will work too.
The documentation contents have been updated to reflect the changes done as part of Multi-accounts revamp.
=> Update Multi-accounts docs

.github/workflows/github-pages.yml, .github/workflows/preview-build.yml
This commit fixes the "Last modified" footer on the pages. Previously they only showed the last commit, because the GitHub action building the static website only checked out the last commit.
With this PR, the action checks out the whole history and can therefore correctly determine the commit which edited the specific page.
Thanks to @viren-nadkarni for noticing / reporting. :)
=> fix last-modified data by fetching repo history in build action

content/en/aws/elasticsearch/index.md, content/en/aws/opensearch/index.md, content/en/aws/ses/index.md, content/en/integrations/kafka/docker-compose.yml, content/en/localstack/configuration.md, content/en/localstack/filesystem.md, content/en/localstack/persistence-mechanism/index.md
- Adds new page describing the new filesystem hierarchy
- Updates references to deprecated vars `DATA_DIR` and `HOST_TMP_DIR` everywhere
Followup to https://github.com/localstack/localstack/pull/6302/
=> New filesystem layout

content/en/aws/opensearch/index.md
While testing for PR #192 , I noticed some inconsistencies in the sample, which are fixed by this PR:
* Domain name in command did not match output or subsequent operations
* Opensearch domain contained `.es.` instead of `.opensearch.`, leading to it being routed to S3.
=> fix opensearch custom cluster sample

content/en/get-started/pro/index.md
The docker port range doesn't seem to reflect the latest port ranges. I have updated it.
=> Update docker port range on pro documentation

content/en/aws/s3/index.md, content/en/get-started/_index.md, content/en/get-started/pro/index.md, content/en/integrations/architect/index.md, content/en/integrations/kafka/docker-compose.yml, content/en/localstack/configuration.md
The `SERVICES` variable is often misused and should not be actively promoted in the documentation, especially in regards with localstack/localstack#6438 .
This removes a bunch of references to the variable, and specifies its newly-introduced limitations in LocalStack.
=> Remove mention of SERVICES except configuration.md

content/en/aws/lambda/index.md
It currently is necessary to have both in the container, which should be documented in the docs.
=> Document requirement of python and bash in container lambdas

content/en/tools/cloud-pods/_index.md
I found a small typo when I was reading the [Cloud Pods documentation](https://docs.localstack.cloud/tools/cloud-pods/).
Note that since this is just a minor documentation change, I didn't setup my local dev environment and I haven't run any tests/linting.
=> Fixed minor typo in Cloud Pods documentation

content/en/aws/rds/index.md, content/en/localstack/configuration.md
Add notes around custom Postgres versions and `RDS_PG_CUSTOM_VERSIONS`. Also added a few section titles, to introduce a bit more structure to the page.
=> Add notes around custom Postgres versions and RDS_PG_CUSTOM_VERSIONS

content/en/aws/cloudfront/index.md
The link was taken directly from the old, on-website docs, and was never adapted.
This PR sets the correct link.
=> Fix cloudfront dns configuration link

content/en/integrations/aws-cli/index.md
Rearrange aws-cli integration documentation.
Push overview into the respective CLI sections and add configuration list option.
=> update aws-cli docs

content/en/localstack/configuration.md
An environment variable I found while looking through the code is missing from the documentation.
This PR adds the documentation for it.
The env was especially useful to me, as I have a situation where I needed to enable this for an application which did not support async (fire and forget) PutRecordAsync requests, in PHP.
Our application stack would severely bottleneck during the PutRecord call performed via the KinesisClient of the AWS PHP SDK.
Setting this env to false completely removed the bottleneck for us, as it enabled treating the Kinesis event source for our Lambda asynchronously. 
I've added this env under the Lambda section as the only usage of this option seems to be within the event source listeners Lambda.
=> Document SYNCHRONOUS_KINESIS_EVENTS environment variable

assets/scss/_styles_project.scss, config.toml, layouts/partials/hooks/body-end.html, layouts/partials/hooks/head-end.html
`docs.localstack.cloud` was accepted for Algolia's DocSearch program!
This PR is in direct competition to #218.
It integrates Algolia search instead of the current "offline" Lunr search.
The search does not have any Ads, has better results, and imho looks way better than the Google Custom Search:
You can play around with it in the preview deployment :)
Let me know what you think!
=> switch from Lunr to Algolia DocSearch

content/en/aws/feature-coverage.md, content/en/aws/logs/index.md
This PR adds docs about CloudWatch Logs, and describes how to use subscription-filter and filter-pattern for metrics, and logs-filtering.
Addresses #219
=> Logs filter pattern

content/en/aws/iam/index.md
Minor: update IAM sample to allow request from root user. Discovered this during testing / preparing an IAM sample - the command `awslocal s3 mb s3://test` actually succeeds with the new version of IAM, as by default we're running requests as the IAM root user. 👍
=> Minor: update IAM sample to allow request from root user

content/en/aws/fis/index.md
The parameter in the code got renamed by https://github.com/localstack/localstack-ext/pull/965.
=> [FIS] Renaming `apiCall` parameter to `operation`

content/en/aws/rds/index.md, content/en/localstack/configuration.md
Update docs around `RDS_PG_CUSTOM_VERSIONS` - the default value is changing from `false` to `true` in the upcoming minor release `1.1.0`.
=> Update docs around RDS_PG_CUSTOM_VERSIONS

content/en/tools/cloud-pods/pods-cli/index.md
Synopsis for status cmd was updated, and would like to reflect the changes in the docs too. Also removed CamelCased spelling of Cloud Pod.
=> [CloudPod] Minor update to status cmd to reflect latest changes

content/en/ci/github-actions/index.md, package.json
Adds info about the conflict between the two python libraries `pyopenssl` (when running an older version) and `cryptography`.
See https://github.com/localstack/localstack/pull/6831#issuecomment-1241974114
=> add info about failing github runners

content/en/localstack/configuration.md
Documents ability to mount local filesystem folders as S3 buckets.
=> DOCS: Add `S3_MOUNT` config variable to docs

README.md, content/en/aws/elastic-kubernetes-service/index.md
* add docs for EKS load balancer ports config (via `_lb_ports_` cluster tags)
* add section and sample for host-based routing
* rename `__k3d_volume_mount__` to `_volume_mount_` and add deprecation notice
=> Add docs for EKS LB ports config and host-based routing

content/en/localstack/configuration.md, content/en/tools/multi-account-setups/index.md
Multi-account will be baked-into the core system from v1.2 and cannot be disabled. This PR removes the defunct flag from the docs.
=> Remove multi-accounts feature flag

content/en/developer-guide/parity-testing.md
`havbe` -> `have` is the only change I really care about :stuck_out_tongue:
=> docs: a few suggested readability improvements

content/en/aws/appsync/index.md
Add resolver types to AppSync docs - to be referenced from 1.2.0 release notes.
=> Add resolver types to AppSync docs

content/en/aws/glue/index.md
Add docs for Glue JDBC crawlers and Redshift integration - should become part of the v1.2.0 release notes.
/cc @silv-io @HarshCasper
=> Add docs for Glue JDBC crawlers and Redshift integration

.github/workflows/lint.yml, .github/workflows/markdown.links.config.json, content/en/ci/github-actions/index.md
Currently the syntax highlighting for Markdown paints everything in the `run` section of the YAML with the same color - `|` at the end of the line for `run` tells YAML that the following indented block is a multi-line scalar literal. That making the commands indistinguishable from comments, so not that visible. It seems to be impossible to fix the color in Markdown.
So rewriting the snippet a bit for a better clarity.
Also fixing the config for markdown-link-check, as currently the tool fails for links to docs.github.com. See https://github.com/tcort/markdown-link-check/issues/201#issuecomment-1110242146 for details.
=> Improving formatting in the GitHub Actions CI snippet.

content/en/aws/cloudfront/index.md, content/en/aws/elastic-load-balancing/index.md
Having mismatched distribution IDs can be confusing to some.
The AWS CLI docs do have matching distribution IDs on the description and the code of their example.
Issue #299
=> Match distribution IDs on CF example

content/en/integrations/aws-cli/index.md
I added a small paragraph about the known limitation when using `--no-sign-request` with the AWS CLI which prevents the request to be routed to the correct service.
Fixes #237
=> Add note about --no-sign-request in AWS CLI

content/en/aws/cloudfront/index.md
I added a brief explanation and a partial example of how to use a custom domain name in a CloudFront distribution.
The example centers only on the part of the message that would set up the domain/domains in CloudFront and omits non-CloudFront details. Please, let me know if this is the right amount of information needed, otherwise I could provide mode details upon request.
Fixes #257
=> Add note and example using cust domain in CF dist

content/en/localstack/configuration.md
The variable is actually named S3_DIR, not S3_MOUNT, so the documentation is wrong.
Change occurrences of S3_MOUNT to S3_DIR.
=> Change S3_MOUNT to S3_DIR

content/en/integrations/pulumi/index.md
Updating the docs to remove the `mobileanalytics` endpoint for pulumi which no longer exists
=> removing: Pulumi mobileanalytics endpoint from docs

content/en/localstack/configuration.md
This PR adds a short section on a config variable introduced with https://github.com/localstack/localstack/pull/7102: `CUSTOM_SSL_CERT_PATH`
=> add docs for CUSTOM_SSL_CERT_PATH

content/en/aws/s3/index.md, content/en/localstack/configuration.md
Fixes #317 
Adds a section in the S3 service documentation about proper usage of the `S3_DIRS` configuration variable with multiple examples.
=> docs: Add documentation for S3_DIRS Environment Variable

content/en/user-guide/aws/appconfig/index.md
This PR:
- Adds starting information to AWS AppConfig
- Add a simple getting started guide
- Link to the configuration page for supported APIs
Preview: https://localstack-docs-preview-pr-344.surge.sh/user-guide/aws/appconfig/
=> add docs for aws appconfig

content/en/user-guide/aws/rds/index.md
add one sentence about RDS minor versions, and a note on the `engine_version` that is returned for db-cluster and db-instances
=> Rds docs update

assets/scss/_styles_project.scss, config.toml, content/en/overview/_index.html, content/en/tutorials/_index.md
adds section to give feedback about articles
can be disabled for single pages via `hide_feedback: true` in frontmatter, as demonstrated by `overview` and `tutorials`
more about this here: https://www.docsy.dev/docs/adding-content/feedback/
=> enable user feedback via GA

content/en/user-guide/tools/cloud-pods/community/index.md, content/en/user-guide/tools/cloud-pods/getting-started/index.md
This PR updates the quick start guide for Pods according to the new CLI workflow. It also contains a link to the Community page introduced with https://github.com/localstack/docs/pull/378
=> Update quick start guide

content/en/overview/_index.html, content/en/tutorials/_index.md, content/en/user-guide/_index.md
Due to some to me unknown reason the fields `hide_readingtime` and `hide_feedback` were removed on a few pages I would have disabled them.
=> Hide readingtime and feedback on some pages

.github/workflows/docs-parity-updates.yml
* Added `input` so that the target branch can be changed for a manual run.
* Changed path to match new `coverage.md` location
=> update github action to update coverage.md

content/en/references/configuration.md
This PR was initiated by https://github.com/localstack/localstack/issues/7275 and it just slightly adjusts the description of the `SMTP_HOST` configuration variable, such that it's a bit more clear that it can contain the SMTP port.
=> describe SMTP port config for SES

config.toml
Docsy limited the number of pages to 50 causing several child pages to be hidden. 
This PR increases the limit making sure they appear in the sidebar and search index.
=> Increase the limit for child pages to display in sidebar

content/en/references/configuration.md
We currently do not have documentation on the variable `DNS_RESOLVE_IP`.
Add documentation on this variable. It has to be made clear that it will override any potential future automatic detection of the proper IP address to be returned by the server.
Addresses localstack/localstack#7355
=> Add dns resolve ip to docs

content/en/contributing/Concepts/index.md
fixes a wrong formatting, which would not correctly link to the resource
=> Fix link formatting for "server"

content/en/references/usage-tracking.md, content/en/user-guide/aws/elastic-container-service/index.md
Add section on ECS task code mounting. Follow-up from https://github.com/localstack/localstack/issues/5941
Also sneaking in a small change with links to Stack Insights, and a note on how to `DISABLE_EVENTS=1` /cc @HarshCasper
=> Add section on ECS task code mounting

content/en/user-guide/aws/iam/index.md
Small update IAM in docs to highlight switching between different terminal sessions, as the administrative IAM commands need to be run with the default root user.
As an alternative, we could also keep it in a single code listing and add switches to temporarily set/unset the access credential environment variables. Feels like it is a bit more clear to have it separated into separate listings with two terminals (as in this PR). Thoughts @dfangl , which one makes more sense?
=> Update IAM docs to use separate terminal sessions for admin commands

content/en/contributing/localstack-extensions.md
Adds the new `on_platform_shutdown` hook to the docs, this will be released with 1.4
=> update extensions doc with on_platform_shutdown hook

content/en/references/multi-account-setups.md
Multi-accounts is not a LocalStack 'tool' per se. It's more appropriate to put it in the same category as 'Persistence'
=> Move multi-accounts to references section

content/en/user-guide/integrations/sdks/go/index.md
While working on a support case, I've tried this example and it didn't work, and we made use of a deprecated function. Updated the sample with the new `EndpointResolverWithOptionsFunc`. See https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/
=> remove deprecated endpoint resolver for go SDK v2 + fix example 

content/en/tutorials/java-notification-app/index.md, content/en/user-guide/aws/cognito/index.md, content/en/user-guide/aws/ses/index.md
This PR updates the docs after some internal endpoints have been adjusted:
- SES Internal API to retrieve emails: https://github.com/localstack/localstack/pull/7630
- Cognito IDP Login / OAuth URLs
The old URLs are still working, but will log a deprecation warning.
=> migrate SES and Cognito IDP login endpoints

content/en/getting-started/quickstart.md
adapt quickstart docs to reflect repository readme file. `make install` is redundant, so I'm not mentioning it anymore.
=> adapt quickstart docs

go.mod, go.sum
There is currently an issue with tabpanes such as [the one underneath this heading](https://docs.localstack.cloud/getting-started/installation/#installation) - clicking multiple times on the "Homebrew" tab causes duplicate rendering of the box below it.
This PR updates the version of docsy which fixes this issue (actually fixed in [this PR](https://github.com/google/docsy/pull/1280)).
We should take the time to make sure this PR is acceptable, given the [change log](https://github.com/google/docsy/blob/main/CHANGELOG.md) mentions some things we may want to investigate:
* ~Tabbed panes, text display. By default, the content of a tab inside a tabbed pane is shown as code. As of version 0.4 of the shortcode, you can add the parameter code=false to your tabpane or tab shortcode in order to …
=> Update docsy to remove rendering bug

content/en/user-guide/aws/elasticsearch/index.md, content/en/user-guide/aws/opensearch/index.md
This PR adds documentation on the support of the Advanced Security Options in the OpenSearch and ElasticSearch service introduced in https://github.com/localstack/localstack/pull/7658.
=> add OpenSearch Advanced Security Options

content/en/user-guide/web-application/stack-insights/index.md
we recently introduced a limitation that stack insights only work for sessions that last less than 24 hours
=> add limitation to stack insights document

content/en/user-guide/aws/mq/index.md
We updated the version in LocalStack to 5.16.6[1] but we did not change
the example.
[1]: https://github.com/localstack/localstack-ext/pull/1382
=> Bump current activemq version

.github/workflows/github-pages.yml
The 18.04 runner is being deprecated, and they have started adding [brownouts](https://github.com/actions/runner-images/issues/6002) disabling builds.
=> Use the latest ubuntu runner

content/en/user-guide/integrations/kafka/docker-compose.yml, content/en/user-guide/integrations/kafka/index.md
clarified an outdated part in the docs (self-managed kafka integration with lambda is also in pro)
Should clarify the following questions:
* https://github.com/localstack/localstack/issues/6121
* https://github.com/localstack/localstack/issues/7219
=> update kafka docs

content/en/user-guide/ci/gitlab-ci/index.md
The Gitlab CI example documentation says "The following example Travis CI job", this PR fixes the typo.
=> Fixed typo in Gitlab CI example

content/en/user-guide/integrations/testcontainers/index.md
Add some details about exposed-port configuration required for RDS. 
Added Java example, and link to pro-samples.
=> add section about testcontainers and RDS

content/en/user-guide/aws/elastic-load-balancing/index.md
Refactor ELB docs to present copy/paste-able command sequence, including assignment of output identifiers to shell variables. 
Also changes the `hashicorp/http-echo` Docker image to `ealen/echo-server`, as the former is not available for ARM64 (and crashes in AMD64 emulation mode) on MacOS. The latter seems reasonably frequently used, and the source code is open source as well. I'm open for other suggestions, though, in case we can find a better / more official image. 👍 
This is in preparation for a reproduction/fix for issue https://github.com/localstack/localstack/issues/7761 .
=> Refactor ELB docs to present copy/paste-able command sequence

content/en/user-guide/integrations/sdks/cpp/index.md
Add docs for AWS C++ SDK - analogous to the other SDKs already covered in our docs.
=> Add docs for AWS C++ SDK

content/en/references/configuration.md, content/en/user-guide/aws/rds/index.md
* Added notes about `arm64` support, which is limited for MySQL and not available for MSSQL at this time. 
* Added missing configuration parameters in the `Configuration` overview
* Added description + example for using IAM authentication
=> add information about arm support + iam authentication for RDS

Makefile, content/en/references/configuration.md, content/en/references/lambda-v2-provider.md, content/en/user-guide/aws/lambda/index.md, content/en/user-guide/aws/s3/index.md, content/en/user-guide/tools/lambda-tools/hot-swapping/index.md
* Adjust provider naming for S3 and Lambda from `asf` to `v2` in line with:
* https://github.com/localstack/localstack/pull/7648
* https://github.com/localstack/localstack/pull/7625
* Add a `Makefile` to automate common commands
=> Change provider naming from asf to v2

content/en/user-guide/aws/s3/index.md
The `S3_DIR` part of the S3 documentation was outdated and using the wrong environment variable. Also added a note concerning the using of `S3_DIR` and `PERSISTENCE=1`. 
fixes #456
=> update S3 S3_DIR documentation

.github/workflows/docs-parity-updates.yml, scripts/get_latest_circleci_metrics.sh, scripts/get_latest_github_metrics.sh
When moving to the new pro pipeline, some of the artifacts required for updating the docs need to be retrieved from different locations:
**Coverage information for pro (capture not-implemented)**
* previously run in CircleCI, with the move only community details are available in CircleCI
* added new job in the workflow to retrieve the artifact
**Metrics Raw Data for pro (test details)**
* previously already retrieved from GitHub, nothing should change here
In this PR:
* updated the workflow
* updated the scripts to retrieve the resources from CircleCI + Github
Open TODOs:
/cc @alexrashed
=> use new artifacts (pro) for Docs Update Workflow

layouts/partials/coverage/coverage_details.html, layouts/partials/coverage/coverage_table.html
The link to `parity-testing` was relative, and pointing to a non-existing page. 
Changed the link to use the path from root.
=> fix dead link to parity-testing details

content/en/user-guide/integrations/sdks/javascript/index.md
Add JS SDK example configuration for a regular client like lambda and for S3, which we could link to in GH issues. 
fixes #533
(page visible here: https://localstack-docs-preview-pr-538.surge.sh/user-guide/integrations/sdks/javascript/)
=> add JavaScript SDK example

content/en/references/configuration.md
Removes a small entry in the configuration reference documenting the `DISABLE_TERM_HANDLER` environment variable. This variable will be removed with 2.0.
This flag has just been introduced to document the changed default behavior (but this "new" default behavior is actually just to correctly handle signals).
=> remove docs on DISABLE_TERM_HANDLER

content/en/user-guide/integrations/sdks/javascript/index.md
It seems we're having issue with AWS JS SDK v2, because it does a weird check to verify if the region is `us-east-1`: instead of checking the client region config, it checks if the endpoint is the global AWS S3 region. 
See related issue here: https://github.com/localstack/serverless-localstack/pull/214
And here: https://github.com/localstack/localstack/issues/8000
Basically, the change is to manually set the globalEndpoint of the client to the hostname of the endpoint configured above to skip the check: `s3.api.globalEndpoint = 's3.localhost.localstack.cloud';`
See https://github.com/localstack/localstack/issues/8000#issuecomment-1488788710
Here's the code in the SDK:
```javascript
createBucket: function createBucket(params, callback) {
// When creating a bucket *outside* the classic …
```
=> add workaround for JS SDK V2

content/en/references/configuration.md, content/en/references/persistence-mechanism.md
This PR updates the [persistence documentation](https://localstack-docs-preview-pr-522.surge.sh/references/persistence-mechanism/) to the current version that uses our new persistence plugin.
There are still some TODOs left to document the current limitations of services
=> update persistence docs

scripts/get_latest_circleci_metrics.sh
prepare workflow to retrieve several raw-metric files from circleci, relates to https://github.com/localstack/localstack/pull/8003:
* Previously, we had a script in CircleCI that was merging the outputs from the tests into one CSV. It also created some coverage information in `html` and `json` format.
* The coverage scripts will now be deleted, because they are not required anymore. 
* CircleCI will now store the artifacts from the test runs without prior modification. 
* This means that the docs update workflow need to retrieve several artifacts for the parity-metrics. The pattern is: `parity_metrics/*.csv`
[Tested the workflow](https://github.com/localstack/docs/actions/runs/4573032265/), by running against companion branch `cleanup_coverage_scripts`:
```
Moving raw community metrics …
```
=> artifact retrieval circleci

scripts/create_data_coverage.py
For some test details, the coverage details does not show a test-node-id. 
This might happen when the metrics have been recorded in between test-execution. E.g. the node-id is set in the python plugin upon test-start. Some services like `cloudwatch` or `dynamodb` could retrieve requests in the meantime.
This PR excludes all tests from showing up in the coverage details if the node-id is empty.
=> fix empty node-ids showing in coverage docs

content/en/user-guide/tools/cockpit/index.md, content/en/user-guide/tools/transparent-endpoint-injection/dns-server.md
Add help for when port 53 is bound on macOS due to `mDNSResponder`.
See conversation here: https://localstack-community.slack.com/archives/C04SFKYDN1E/p1680286599737779
=> Document mDNSResponder on macOS

content/en/references/configuration.md
=> EC2: Add config option to disable Docker images retrieval

content/en/user-guide/integrations/testcontainers/index.md
This PR updates the Testcontainers for .NET generic container configuration of LocalStack and replaces it with the corresponding module. Using the module is much easier for developers, as it requires fewer configurations and comes with best practice configurations pre-configured.
=> docs: Replace the generic LocalStack container with the corresponding module

content/en/user-guide/aws/iot/index.md
Introduces sections to IoT docs and adds documentation related lifecycle events.
Jump to <https://localstack-docs-preview-pr-557.surge.sh/user-guide/aws/iot/>
=> IoT: Add lifecycle events

content/en/references/arm64-support/index.md, content/en/references/configuration.md, content/en/references/lambda-executors.md, content/en/references/lambda-provider-v2.md, content/en/user-guide/aws/lambda/index.md, content/en/user-guide/tools/lambda-tools/hot-reloading/index.md, content/en/user-guide/tools/transparent-endpoint-injection/patched-sdks.md
* Refine formulation and improve consistency (e.g., LocalStack v2 => 2.0)
* Add highlights to Lambda v2 docs + link discuss post
* Emphasize deprecation notes in page titles
* Adjust Docker not available error message to match released version
* Clarify that multi-arch Lambda support is only v2
=> Polish lambda v2 docs

.github/workflows/docs-parity-updates.yml, layouts/partials/coverage/coverage_details.html, layouts/partials/coverage/coverage_table.html, layouts/partials/coverage/coverage_table_row.html, scripts/create_data_coverage.py
Adds the terraform test results to the Coverage Docs table to indicate that an operation was run using terraform.
- Adapted the workflow to download artifacts from `localstack-terraform-test` project
- Added new column to the table
TODO:
- tested workflow, resulting PR https://github.com/localstack/docs/pull/571 and preview can be checked here: https://localstack-docs-preview-pr-571.surge.sh/references/coverage/coverage_sqs/
=> inclusion of terraform test results in Coverage Docs

content/en/user-guide/aws/sqs/index.md
Linked Issue: https://github.com/localstack/docs/issues/584
Changes:
- Renamed duplicated heading title in SQS docs
- Fixed name of link to AWS docs
=> Fix Typo In SQS Docs

content/en/references/configuration.md, content/en/user-guide/aws/cognito/index.md
Add docs for two recently added features:
* `EKS_K3S_IMAGE_TAG` in EKS - allowing to specify a custom image tag for the Rancher k8s image when creating Kube clusters. /cc @alexrashed  
* `_custom_id_` in Cognito - allowing to specify custom IDs on user/identity pool creation. /cc @giograno
=> Add docs for EKS_K3S_IMAGE_TAG and _custom_id_ in Cognito

data/developerhub/applications.json
Removing `serverless` from title and description of sagemaker sample since the sample now provides a non-serverless endpoint by default.
=> remove serverless from title and description of sagemaker sample

content/en/references/configuration.md, content/en/references/credentials.md, content/en/references/multi-account-setups.md
This PR adds missing documentation regarding access key IDs.
Jump to content: https://localstack-docs-preview-pr-613.surge.sh/references/credentials/
See:
- https://github.com/localstack/localstack/issues/8225
- https://github.com/localstack/localstack/pull/7093#discussion_r1185691341
=> Add credentials documentation

content/en/user-guide/aws/lambda/index.md
This  PR proposes using `LayerVersionArn` instead of manually appending `:1` to the ARN to simulate a version number (missing it off results in a regex match failure message, causing `lambda create-function` to fail; you can guess how I know this!)
Not directly relevant for the current examples, but using the versioned ARN string will also simplify updating a layer and running `update-function-configuration` as it should provide the reference for the freshly updated layer with no further effort for the user.
Related issue: https://github.com/localstack/docs/issues/617
=> Simplify lambda layer creation

content/en/user-guide/aws/sqs/index.md
Fixes issue #634
According to the [credentials docs](https://docs.localstack.cloud/references/credentials/), the account-id must be a valid 12-digit number or an alpha-numeric string and the default 000000000000 is used as a fallback.
=> Fixes error in sqs user guide

content/en/references/network-troubleshooting/endpoint-url/_index.md
This PR adds documentation regarding wildcard DNS mapping.
Docker does not support mapping `*.localhost.localstack.cloud` to a container. This is required for e.g. virtual host addressing of S3 buckets (`<bucket>.s3.<region>.localhost.localstack.cloud`) or API Gateway urls (e.g. `<apiid>.execute-api.localhost.localstack.cloud`).
This document describes how to achieve this domain mapping by configuring docker containers to use the LocalStack container as their DNS server.
**Preview**: https://localstack-docs-preview-pr-629.surge.sh/references/network-troubleshooting/endpoint-url/#wildcard-dns-access
=> Document wildcard DNS access

content/en/references/arm64-support/index.md, content/en/references/configuration.md, content/en/references/coverage/_index.md, content/en/references/credentials.md, content/en/references/custom-tls-certificates.md, content/en/references/docker-images.md, content/en/references/external-ports.md, content/en/references/filesystem.md, content/en/references/init-hooks.md, content/en/references/internal-endpoints.md, content/en/references/localstack-cli-manual.md, content/en/references/localstack-extensions.md, content/en/references/localstack-on-kubernetes.md, content/en/references/logging.md, content/en/references/multi-account-setups.md, content/en/references/network-troubleshooting/_index.md, content/en/references/persistence-mechanism.md, content/en/references/podman.md, content/en/references/usage-tracking.md
This PR fixes the ordering of Reference pages into alphabetical order. This makes it easier to find the page one is looking for.
The Configuration page is retained at the top.
Furthermore, it also makes the page summary of each page consistent in wording and styling.
=> Fix ordering of reference pages

config.toml
This PR disables the taxonomy feature of Hugo and hides the 'Categories' and 'Tags' section in the sidebar and page frontmatter.
We currently have no system in place for categories and tags. As a result, there is a confused mixture of taxonomies in majority of documentation pages. 
Disabling this gives our docs a cleaner and less busy look, hopefully making them more approachable and presentable to new users.
If we reconsider this change in the future, it is easy to enable it by reverting this commit. The tags and categories in individual pages are not removed.
=> Disable taxonomies

scripts/create_data_coverage.py
Latest [failing workflow for updating the docs](https://github.com/localstack/docs/actions/runs/5308007605/jobs/9607061813), revealed that community results might have operations included, that pro doesn't have yet. This could be as we consider the latest successful master build, and the repositories are split.
Fixed the KeyError issue, by setting defaults.
=> fix script for docs update

content/en/user-guide/tools/lambda-tools/debugging/index.md
When running a Lambda in a Docker container, we need to listen to any host and not only to `127.0.0.1` by default (see [listen](https://github.com/microsoft/debugpy/blob/main/src/debugpy/public_api.py#L94) implementation).
=> Fix Lambda debugging instructions for Python listen

content/en/user-guide/integrations/testcontainers/index.md
The recommended way to use the Testcontainers class is
`new LocalStackContainer(DockerImageName.parse("localstack/localstack:2.1.0"))`
=> Fix Java code snippets

content/en/references/configuration.md
LocalStack deprecated several network related variables in https://github.com/localstack/localstack/pull/7893 but this was not reflected in the docs causing some confusion among users. This PR updates the config variable section.
Closes: https://github.com/localstack/docs/issues/615
=> Update deprecated config options

content/en/user-guide/aws/elastic-compute-cloud/index.md
A user pointed out that it was not clear that the `daemons` command is available only after logging in. I added this instruction to hopefully avoid support tickets related to this in the future. regardless of whether or not it goes away in the future, for now it's beneficial.
=> add instructions on how to have daemons command available for pro

content/en/references/configuration.md
Add docs for `ECS_DOCKER_FLAGS`, including a small update in `LAMBDA_DOCKER_FLAGS` mentioning the new DNS server config support (see [here](https://github.com/localstack/localstack/pull/8697)).
=> Add docs for ECS_DOCKER_FLAGS, including DNS server config

config.toml
Changes the latest_version to 2.2.0, for parts of the documentation + cli download links.
Should be merged after 2.2.0 release is finished.
=> Update LocalStack version to 2.2.0

content/en/user-guide/aws/timestream/index.md
this is a very minimal reformat of the timestream docs, such that it conforms with our new template.
Note: Timestream is actually available via the resource-browser, however it's currently not working. Therefore, I would prefer not to advertise it.... obviously due to change once it works again
=> reformat docs for timestream

content/en/user-guide/aws/eventbridge/index.md
Fixes a grammatical error and makes the filename in the prose match the one in the command below.
Relevant page/section: https://docs.localstack.cloud/user-guide/aws/eventbridge/#add-the-lambda-function-as-a-target
=> Fix typo in instructions for adding target to EventBridge

layouts/partials/coverage/coverage_table.html, layouts/partials/coverage/coverage_table_row.html
Skip the "external-test-suite" column for lambda in the coverage-overview, as we do not have any external tests.
Initially the column for "external tests" was added to show an improvement of the coverage. Mainly for services where we rely on moto, and which are therefore covered by moto-tests. 
However, for lambda this does not make sense, as the external test suite is not working, but do we have all tests covered internally (which is the end goal anyhow).
As the table looked now lambda is missing tests (which it doesn't), we decided to take the approach of excluding the "external test suite" for now with @joe4dev. Other services could be added to the exclusion. 
/cc @HarshCasper @whummer
=> coverage table enhancement for lambda

content/en/references/custom-tls-certificates.md
This PR adds the NodeJS Custom CA cert config to the ["Custom TLS Certificates"](https://docs.localstack.cloud/references/custom-tls-certificates/) docs page.
This is necessary, since we use NodeJS for some services, for example to download the `kinesis-mock` package using `npm`.
=> add NodeJS config to "Custom TLS certificates"

content/en/user-guide/tools/lambda-tools/debugging/index.md
This new debugging setup is now compatible with both the legacy and the new provider as well as different Java runtimes.
=> Update JVM debugging docs

content/en/references/network-troubleshooting/endpoint-url/_index.md, content/en/user-guide/aws/iot/index.md, content/en/user-guide/aws/ses/index.md, content/en/user-guide/tools/cloud-pods/_index.md
Adds a hint in the IOT page:
---
=> Clarify LocalStack lazy loading behaviour wrt MQTT broker

content/en/user-guide/aws/athena/index.md
Add initial docs for Delta Lake tables in Athena. Documentation for a feature that has recently been added in -ext.
Also added a placeholder for Iceberg tables, as I realized they are not covered in our docs yet. More details following there soon (in a separate PR).
=> Add initial docs for Delta Lake tables in Athena

content/en/references/configuration.md, content/en/user-guide/aws/elastic-compute-cloud/index.md
* Add docs for attaching EBS block devices to EC2 instances
* Add entries for new configuration variables to EC2 config section
* Slightly revise the description around SSH connections for EC2 instances, to make them more self-contained. The docs now also contain a pointer to the `import-key-pair` command, which can be used to import an existing local SSH public key, to connect to the instance with the corresponding private key.
/cc @viren-nadkarni @cabeaulac
=> Add docs for attaching EBS block devices to EC2 instances

.github/dependabot.yml, .github/workflows/docs-parity-updates.yml, .github/workflows/github-pages.yml, .github/workflows/lint.yml, .github/workflows/preview-build.yml
This PR performs the same actions as https://github.com/localstack/localstack/pull/9065, just for the docs repo.
We are still seeing build issues related to https://github.com/actions/checkout/issues/1448, even though the incident should already be fixed (according to https://www.githubstatus.com/).
Some comments in this issue imply that an upgrade to the just newly released version 4 of [actions/checkout](https://github.com/actions/checkout) might fix the issue.
I used this opportunity toi also 
- Upgrades all usages of [actions/checkout](https://github.com/actions/checkout) to version 4.
- Add GitHub actions to the dependabot config to file these upgrade PRs automatically in the future.
=> upgrade to actions/checkout@v4, add actions to dependabot

assets/scss/_styles_project.scss, content/en/user-guide/integrations/crossplane/index.md, content/en/user-guide/integrations/crossplane/logo-crossplane.svg, content/en/user-guide/integrations/terraform/index.md, layouts/shortcodes/command.html, static/js/global-script.js
Add tutorial on using [Crossplane](https://crossplane.io/) AWS provider with LocalStack. Motivated by a recent user request in the Discuss forum: https://discuss.localstack.cloud/t/crossplane-integration/507 (addresses point (2) in my response in the thread)
As a follow-up, it would be great if we can update the overview figure in our [integrations page](https://docs.localstack.cloud/user-guide/integrations/) - it is a bit outdated at this point, and a couple more integrations have been added in the meantime. @HarshCasper maybe we can work with @lazarvu on that - we also have a figure in our customer deck that we can build upon. 👍 
---
@HarshCasper I was trying to follow your advice on not using multi-line `<command>` listings that also contain the command output (to prevent users from …
=> Add tutorial on using Crossplane AWS provider with LocalStack

assets/scss/_styles_project.scss, layouts/shortcodes/command.html
This PR fixes a reported bug (screenshot attached below) in the newly created "disable-copy" feature as it was acting weird with new lines.
=> Fixed "disable copy" feature bug

content/en/user-guide/aws/transfer/index.md
This PR updates the user guide on AWS Transfer to make it follow the template and I wrote a more simple template than the Pro sample that was referenced previously.
=> improve docs on aws transfer

content/en/user-guide/aws/sqs/index.md
Small PR that fixes the queue names in the sqs docs (so they are consistent and directly copy&pastable)
Also small nit correction, if an output contains a random id it can of course be never exactly the same as the id we wrote down.
=> fix queue names

content/en/user-guide/aws/security-token-service/index.md
Encountered a tiny snippet syntax error that broke syntax highlighting.
Fix it and normalized display of output payload.
Thanks for your work !
=> fix syntax error in snippet

content/en/user-guide/aws/neptune/index.md
Updating the Neptune docs according to our new standardized template.
* Added samples on how to create DBCluster and instance using aws-cli.
* Added little python script that creates a graph + queries the database and prints the result
=> update neptune docs

content/en/user-guide/aws/mediastore/index.md
A user guide for AWS Elemental MediaStore
=> MediaStore guide

content/en/references/init-hooks.md
The initialization hooks are a nice and widely used feature of LocalStack (for example in order to pre-seed an environment when starting up).
However, the file setup with the mounts, executable flags, and shebang headers triggered some issue reports over the time:
- https://github.com/localstack/localstack/issues/9127
- https://github.com/localstack/localstack/issues/8797
- https://github.com/localstack/localstack/issues/8688
- https://github.com/localstack/localstack/issues/8127
- https://github.com/localstack/localstack/issues/8048
- https://github.com/localstack/localstack/issues/7751
- https://github.com/localstack/localstack/issues/7596
- https://github.com/localstack/localstack/issues/7289
- https://github.com/localstack/localstack/issues/7134
- …
=> add troubleshooting guide to init hook docs

content/en/user-guide/tools/lambda-tools/debugging/index.md, content/en/user-guide/tools/lambda-tools/hot-reloading/index.md
Addresses:
* https://github.com/localstack/docs/issues/785
* https://github.com/localstack/localstack-pro-samples/issues/224
The default Lambda invoke command with an inline payload such as `--payload '{"message": "Hello from LocalStack!"}'` works only for AWS CLI v1. The AWS CLI v2 needs an extra argument `--cli-binary-format raw-in-base64-out`, which is not available in the AWS CLI v1.
The Lambda documentation uses a tabpane to provide commands for both CLI versions: https://docs.localstack.cloud/user-guide/aws/lambda/#invoke-the-function
This PR makes all Lambda invoke commands using an inline payload compatible with AWS CLI v2 by using a tabpane.
This tabpane approach seems quite cumbersome and we should try to avoid using inline payloads where possible to minimize using them.
=> Fix lambda invoke commands with inline payload for AWS CLI v2

content/en/getting-started/api-key.md, content/en/getting-started/faq.md, content/en/user-guide/aws/feature-coverage.md, content/en/user-guide/aws/lambda/index.md, content/en/user-guide/aws/xray/index.md
* Update the X-Ray docs with the new template.
* Completely re-write the docs: Add a new generic X-Ray tutorial section instead of the Lambda-related snippet.
* Link to the new lambda-xray pro samples in https://github.com/localstack/localstack-pro-samples/pull/226
https://localstack-docs-preview-pr-823.surge.sh/user-guide/aws/xray/
=> Enhance docs for xray

content/en/getting-started/api-key.md, content/en/getting-started/installation.md
Add some clarity to the getting started page.
- Make getting started sections consistent community vs pro
- Include section on what the CLI does
- Remove the word "just"
- Add curl example commands
=> Clarify installation page

content/en/user-guide/aws/elastic-compute-cloud/index.md, content/en/user-guide/aws/iot/index.md
This PR standardises the page structure and adds detailed usage of the multiplexed MQTT broker endpoint.
https://localstack-docs-preview-pr-813.surge.sh/user-guide/aws/iot/
=> Revamp IoT docs

.github/workflows/docs-parity-updates.yml, content/en/contributing/development-environment-setup.md
This PR updates the development environment setup guide with the changes with https://github.com/localstack/localstack/pull/8087:
- LocalStack now uses Python 3.11.
- LocalStack does not need `libsasl2` anymore.
It also updates the Python version in the Docs Update action.
=> update to Python 3.11

content/en/user-guide/aws/s3/index.md
S3 endpoints are a source of confusion for our users ( we must have had at least 4 GH issues in the past regarding this issue, + community slack), as most SDKs will now use virtual hosted requests to access LocalStack. However, trying to access a bucket with `bucket.localhost.localstack.cloud` or `bucket.localhost` won't work in most cases. Added a bit more explanation in the documentation about the configuration, and put a link to the SDKs where most of them have the S3 specific case and endpoint explained. 
preview page: https://localstack-docs-preview-pr-834.surge.sh/user-guide/aws/s3/#path-style-and-virtual-hosted-style-requests
=> update S3 endpoint docs

content/en/user-guide/aws/batch/index.md
This PR adds a user guide for AWS Batch. It walks through creating the compute infrastructure required, and submitting a job to the queue.
=> Add AWS batch user guide

content/en/references/cross-account-access.md
Adds info on cross-account/region VPC peering.
Also sorts section alphabetically.
Related to https://github.com/localstack/localstack/issues/8550
=> Add info on cross-account/region VPC peering

config.toml, content/en/references/configuration.md
To be merged after 2.3 release
=> Update user docs to v2.3

content/en/getting-started/faq.md, content/en/getting-started/installation.md, content/en/references/network-troubleshooting/created-resources/_index.md, content/en/references/network-troubleshooting/endpoint-url/_index.md, content/en/references/network-troubleshooting/transparent-endpoint-injection/_index.md, content/en/user-guide/tools/transparent-endpoint-injection/dns-server.md
Users who have issues connecting their application to LocalStack may need to use the network troubleshooting guide, however this guide is not very discoverable. It's in the references section. Also we have made updates/improvements to our networking story with LocalStack 2.3, but this is not reflected in the documentation.
* Link to the network troubleshooting guide from the installation docs
* Update the network troubleshooting guides to refer to `localhost.localstack.cloud` if possible
* Update the FAQ entry for `localhost.localstack.cloud`
=> Update networking documentation for 2.3

content/en/user-guide/aws/elastic-kubernetes-service/index.md, static/js/global-script.js
When starting an EKS cluster, I was copying the commands from the docs but the output was copied along with the commands.
* Split the command and output into separate code blocks
=> Split EKS commands and outputs for better copy and paste

content/en/user-guide/aws/elastic-load-balancing/index.md
While running the elb sample instructions figured out that in some cases we might to give the target id while registering the target as the `Gateway` address of the docker container.
=> update elb docs 

content/en/references/configuration.md
* Document Lambda limit `LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE` as requested in https://github.com/localstack/localstack/issues/7074#issuecomment-1722971824
> We just want to be able to allow our users to create/upload big Lambdas, ideally without having to implement some non trivial workaround like uploading them to S3 or similar.
* Link to the migration guide rather than the generic Lambda page regarding the new Lambda provider
=> Add Lambda limits configuration for `LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE`

content/en/user-guide/aws/lambda/index.md
The Lambda documentation does not clarify that "Lambda layers" is a Pro feature.
We should be consistent with the coverage docs marking "Lambda layers" as a Pro feature: https://docs.localstack.cloud/user-guide/aws/feature-coverage/
* Add `(Pro)` to the Lambda layers title to be consistent with the coverage docs
* Clarify the behavior by explaining that CRUD still works in LocalStack Community but usage is Pro
* Fix phrasing (layers cannot be invoked)
=> Clarify Lambda layers pro feature

data/coverage/service_display_name.json
Updates the content of `service_display_name.json` which is used for the coverage docs pages.
With the updated content the search will also include the long-service names, and we provide the link to the API reference along in the details page of the coverage service.
This will only be visible for the next docs-update, which runs with the scheduled workflow on Sundays.
=> update metadata for generation of coverage docs

content/en/user-guide/aws/elastic-container-registry/index.md
Fixes https://github.com/localstack/docs/issues/844 and https://github.com/localstack/docs/issues/858
Change `localhost` to `localhost.localstack.cloud` matching the remainder of the docs.
Tested updated version locally ✅
=> Fix mismatching Docker image tag

content/en/user-guide/ci/harness-ci/index.md
The `/health` endpoint has been deprecated for quite a while and will be removed with `3.0`.
This PR migrates to the new endpoint (`/localstack/health`).
=> avoid deprecated health endpoint

content/en/references/persistence-mechanism.md
This PR removes a duplicate entry for the `SCHEDULED` persistence strategy.
Thanks to @whummer for noticing it!
=> fix scheduled strategy docs

content/en/user-guide/aws/iot/index.md
This PR makes all examples use the port returned by IoT:DescribeEndpoint
=> IoT: Fix incorrect port in example

content/en/references/configuration.md
This PR updates the docs to reflect the changes made in https://github.com/localstack/localstack/pull/9375 and https://github.com/localstack/localstack/pull/9374
=> Remove DEFAULT_REGION and USE_SINGLE_REGION

content/en/user-guide/aws/elastic-compute-cloud/index.md
The EC2 local daemon will be removed in the upcoming v3 release.
This removes the outdated portions of user docs. It also highlights some other important lines in alert boxes so that they stand out.
=> Remove EC2 local daemon

content/en/user-guide/aws/sqs/index.md
With the changes introduced in https://github.com/localstack/localstack/pull/9468, the PR updates all examples to reflect the new default SQS endpoint strategy.
From `path` strategy:
`http://localhost:4566/000000000000/localstack-queue`
to `standard` strategy:
`http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/localstack-queue`
=> Change SQS endpoint examples

content/en/user-guide/aws/iot/index.md
With LocalStack v3, IoT MQTT broker addresses contain the account ID and region.
=> IoT endpoint are now fully qualified

content/en/references/configuration.md, content/en/user-guide/aws/elasticache/index.md
This PR adds additional examples to illustrate the abilities of the new ElastiCache provider.
=> New Elasticache provider

.github/workflows/markdown.links.config.json, content/en/getting-started/faq.md, content/en/getting-started/installation.md, content/en/references/configuration.md, content/en/references/docker-images.md, content/en/references/external-ports.md, content/en/references/init-hooks.md, content/en/references/network-troubleshooting/endpoint-url/_index.md, content/en/user-guide/aws/opensearch/index.md, content/en/user-guide/extensions/managing-extensions/index.md, content/en/user-guide/tools/transparent-endpoint-injection/dns-server.md
Hyphens are not allowed in URLs. When addressing the LocalStack container over a docker network, the container name resolves to the IP address of the container. This is a problem in particular for boto3 which refuses to connect.
This PR updates usages of `localstack_main` to `localstack-main`.
=> Major: rename default container name to localstack-main

content/en/user-guide/aws/iot/index.md, content/en/user-guide/aws/neptune/index.md
It seems merging #892 broke the broken link checker. This may be because the config file previously had an incorrect format, and was therefore invalid JSON, however it is confusing that the pipeline did not fail at any point.
Regardless, some broken links were found:
* the use of `local.localstack.cloud` (rather than `localhost.localstack.cloud`)
* links to removed neptune API reference
This PR fixes the two points listed above, and fixes the broken link checker.
=> Fix CI broken link checks

content/en/references/configuration.md
Introduces a new partitioning of older configuration values to unify how we communicate their deprecation status.
1. `Deprecated` ... Still supported in latest version but should not be used anymore. Will be removed in one of the next major releases.
2. `Legacy` ... Has been removed in a previous major release. Does **NOT** affect the latest version anymore.
We should probably also cover variables we've just removed from the list in the past.
This isn't super urgent but we should make sure we sync the deprecation status here with the ones we're tracking in localstack.
=> Partition old configuration into deprecation/legacy

content/en/references/configuration.md
Following #906, I moved the S3 configuration for the legacy provider in the dedicated section. This helps tremendously, as it would have been confusing in the regular S3 section, thanks @dominikschubert!
Preview:
https://localstack-docs-preview-pr-908.surge.sh/references/configuration/#s3
https://localstack-docs-preview-pr-908.surge.sh/references/configuration/#deprecated
=> update S3 config with new legacy partition

content/en/getting-started/faq.md
Added details how to use Git Bash with LocalStack to prevent unnecessary errors.
=> Add Git Bash information

content/en/references/configuration.md, content/en/user-guide/aws/docdb/index.md
Add details about new flag `DOCDB_PROXY_CONTAINER`, add lambda-sample.
=> Update DocDB docs

scripts/create_data_coverage.py
With the introduction of the json protocol for SQS and the [fix in LocalStack](https://github.com/localstack/localstack/pull/8268/files), the [coverage update from this week](https://github.com/localstack/docs/pull/909) was showing `sqs-query` and `sqs` as two different services. 
However, showing the coverage like this doesn't make sense. 
This PR adapts the coverage-scripts so that `sqs-query` will not be listed as a separate service, and all metrics recorded for service `sqs-query` will be added to the `sqs` service.
Started a [test run with the feature branch](https://github.com/localstack/docs/actions/runs/6864103913), resulting in this [PR](https://github.com/localstack/docs/pull/914), where we don't see service `sqs-query` anymore.
=> Fix sqs coverage

content/en/user-guide/integrations/pulumi/index.md
Update Pulumi docs with new option in pulumi-local
- Added new AWS_ENDPOINT_URL
- Marked LOCALSTACK_HOSTNAME and EDGE_PORT deprecated
=> Add AWS_ENDPOINT_URL to pulumi docs

CODEOWNERS, content/en/user-guide/integrations/terraform/index.md
Update Terraform docs with new option in terraform-local
- Added new AWS_ENDPOINT_URL
- Marked LOCALSTACK_HOSTNAME and EDGE_PORT deprecated
- Introduced default value column for better readability
- Add myself as CODEOWNER to pulumi and terraform
=> Add AWS_ENDPOINT_URL to terraform docs

content/en/references/configuration.md, content/en/user-guide/aws/lambda/index.md
Preview here: https://localstack-docs-preview-pr-918.surge.sh/references/configuration/#legacy
Follow up to https://github.com/localstack/docs/pull/906 where I started to partition the deprecated configuration variables into `deprecated` and `legacy`. 
I've started collecting old configuration values and when they have been removed/deprecated. I'll probably need some help verifying them but for now it should provide a good starting point.
cc @tinyg210 you've expressed interest in this in our meeting on Monday
- Collected old configuration variables which are not supported anymore
- Tried to figure out when certain configs were deprecated or removed
- Undeprecated `HOSTNAME_FROM_LAMBDA`
- Removed **Deprecations** section in favor of having them in their respective sections again. I agree …
=> Collect more legacy configurations

config.toml
Version 3.0.1 has been released.
This PR updates the CLI version output, as well as the links in the instructions to point towards the new release.
=> update the CLI version and links to 3.0.1

content/en/user-guide/cloud-pods/pods-cli/index.md
This PR updates the CLI reference for Cloud Pods.
I also added a section for local commands (`localstack state import/export`). 
We still have the Community Pods page up, although we mark them as deprecated. Should we drop the page?
Looking for feedback.
=> update pods cli docs

CODEOWNERS, content/en/user-guide/aws/route53/index.md
A user in our [#help channel](https://localstack-community.slack.com/archives/CMAFN2KSP/p1701724951011449) was following the docs for Route53 and understandably thought that updating DNS records was in the Community version of LocalStack.
* Update the documentation to describe that updating DNS records is a Pro feature.
* Reorganise the structure a bit to split the community (CRUD operations on hosted zones and record sets) from pro (dns resolution)
* Update codeowners for the network troubleshooting guide and DNS server pages
=> Update Route53 Pro DNS server updating

content/en/references/configuration.md, content/en/user-guide/tools/dns-server/_index.md
With https://github.com/localstack/localstack/pull/9692 we deprecated the use of `DNS_LOCAL_NAME_PATTERNS` since it had a confusing name. Instead of _adding_ domain name patterns to resolve to LocalStack, it added domain names to the skiplist of names that should always be resolved upstream. In particular, with transparent endpoint injection enabled, `s3.amazonaws.com` would resolve to LocalStack, and `DNS_LOCAL_NAME_PATTERNS` could force LocalStack to resolve the name from its upstream resolver.
* Update all usages of `DNS_LOCAL_NAME_PATTERNS` to use the new `DNS_NAME_PATTERNS_TO_RESOLVE_UPSTREAM` variable
=> Update docs for upstream resolution patterns

content/en/user-guide/integrations/pulumi/index.md
Pulumi example contained wrong path style switch that throws an error with new package version.
I reported the issue to Pulumi too, which they have applied already.
https://github.com/pulumi/pulumi-aws/issues/3068
- swap `s3ForcePathStyle` to `s3UsePathStyle`
=> Add fix on pulumi example

content/en/user-guide/integrations/cdk-for-terraform/index.md
We got the request to include Python example into our quickstart docs which would make the experience more consistent for anyone starting with CDK for Terraform on Localstack
- Removed duplicate lines
- Language neutral project
- Python quickstart
=> Python example in CDKTF Quickstart

content/en/tutorials/s3-static-website-terraform/index.md
As pointed out by a user, the tutorial for hosting a static website using an S3 bucket is using a redundant 'www' folder. The text has been adjusted to not use that anymore, due to better parity with the real service.
I've also changed a few expressions to make the text feel more relaxed.
=> remove unneeded 'www' folder (due to better parity it's redundant)

content/en/user-guide/aws/identitystore/index.md
This PR adds docs for `identitystore` service that is shipped out in the `localstack/localstack-pro:latest` image this week
=> add docs for identity store

content/en/user-guide/aws/acm/index.md
This PR adds docs for `acm-pca` service that is shipped out in the `localstack/localstack-pro:latest` image this week
=> add docs for acm pca

content/en/references/configuration.md, content/en/user-guide/aws/sqs/index.md
Adds accompanying docs for the new `MessageRetentionPeriod` feature https://github.com/localstack/localstack/pull/9956
=> add docs for SQS message retention period

content/en/references/configuration.md
Update increased Lambda runtime environment timeout from `10` to `20` seconds.
Changed with https://github.com/localstack/localstack/pull/9972
=> Update new Lambda runtime environment timeout

.github/workflows/docs-parity-updates.yml, scripts/get_latest_github_metrics.sh
Previously, we used the same artifact ID for the parallel metrics collection in our internal test suite on GitHub. This means both jobs executed in parallel would use the same ID (the first one to finish creating the artifact, the second one to append to it).
But we recently upgraded to the latest major version of `actions/upload-artifact` in our internal test pipelines, and this major version enforces that every artifact is immutable (which forced us to use multiple artifact IDs for the metrics).
This PR adjusts the scripts and GitHub workflow to update the Partiy Docs such that they use a pattern when downloading the artifacts from GitHub instead. 
When using the pattern, a subfolder for each artifact is created, which is why the glob patterns for the file movements are also slightly …
=> fix parity docs action after github actions upgrade

content/en/user-guide/lambda-tools/hot-reloading/index.md
While I was looking into restoring a state with a hot-reloading lambda function, I noticed that the function we mention is outdated/misplaced (see https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/python/example_code/lambda/lambda_handler_basic.py).
This small fix would make the sample work.
=> minor fix to lambda hot-reloading docs

content/en/user-guide/aws/neptune/index.md
Small typo fix in link, which make it not work until you remove it from the url 😋
=> Fixed typo in Neptune link in index.md

content/en/user-guide/aws/managed-streaming-for-kafka/index.md
This will address the issue of Kafka cluster interaction being broken due to the mismatch between the versions of Kafka in LocalStack and the version mentioned in the documentation.
=> Update Kafka version to 2.8.0

content/en/user-guide/aws/sqs/index.md
Adds documentation for https://github.com/localstack/localstack/pull/9988. I added a complete end-to-end example on DLQ testing.
I did feel this is somewhat of a slippery slope towards replicating the AWS docs, but I think having the full example helps showcase how sophisticated the implementation is :+1:
=> add example for DLQ redrive testing

data/developerhub/applications.json, data/developerhub/platforms.json, data/developerhub/services.json
Add Route53 failover with FIS & Building resilient systems with FIS experiments, for now.
I excluded the extension for now, as it uses the Pet/Food Store sample, and it's not a standalone example.
=> add chaos engineering samples

layouts/partials/page-meta-links.html
In the past, we decided to remove the edit button from the docs pages.
But recently, we have seen that it might be useful to have a fast and easy way to propose changes to the docs.
This PR re-enables the edit button, which has been disabled in a rework of the sidebar in https://github.com/localstack/docs/pull/528 by @lukqw.
This should be used as the start of a discussion, and we can use the preview environment to play around with it.
I used the preview environment to create a short screencast of the feature used to create https://github.com/localstack/docs/pull/1031:
[Screencast.webm](https://github.com/localstack/docs/assets/2796604/a5ab8287-2588-4787-83ed-c8e054f3b040)
~~I explicitly made this a draft PR for now to make sure that we explicitly decide on re-enabling this feature.~~ …
=> re-enable edit link

content/en/user-guide/ci/github-actions/index.md
The CI key is using the LOCALSTACK_API_KEY environment variable. To avoid potential confusion, I've updated the documentation to reference LOCALSTACK_API_KEY instead of LOCALSTACK_AUTH_TOKEN.
Following: https://docs.localstack.cloud/getting-started/auth-token/#configuring-your-ci-environment
=> Update AUTH_TOKEN to API_KEY in GitHub Actions

content/en/getting-started/changelog.md, content/en/references/changelog.md
I was looking into docs analytics today and saw some folks have been looking for a Changelog on our docs. Currently, we have changelogs on Discuss for our minor releases. 
This PR:
- Adds a new changelog page
- Links it over the references section
- Documents every single major & minor release since 1.0
=> add a changelog page

content/en/user-guide/ci/codebuild/index.md
This PR adds docs on Codebuild and how to specify the `buildspec.yml` file.
Preview: https://localstack-docs-preview-pr-1060.surge.sh/user-guide/ci/codebuild/
=> add docs on codebuild

content/en/references/configuration.md
An upcoming feature of ECS is that we will inject `AWS_ENDPOINT_URL` into the users' container environment. This is a change to the defaults, so we must provide a configuration flag (`ECS_DISABLE_AWS_ENDPOINT_URL`) to restore the previous behaviour. 
This change documents that new flag, taking inspiration (i.e. copied from) the `LAMBDA_DISABLE_AWS_ENDPOINT_URL` variable.
=> Document ECS_DISABLE_AWS_ENDPOINT_URL

content/en/getting-started/faq.md
The FAQ item for "Why is it that LocalStack is unable to connect to the internet" could do with expanding upon. It only suggests one thing, and links to outdated documentation.
* Mention the `none` network driver, and ensure users are not using it
* Describe debugging the connectivity with `docker inspect ... ` and check for IP addresses
* Update the documentation to mention the bridge network specifically
Unfortunatley this is such a general question, and is not really in the scope of LocalStack, it is a docker networking problem. This means
* if we provide an FAQ item, we cannot cover all options
* perhaps this item should be removed, as it is not a LocalStack specific problem?
=> Update FAQ page on internet connectivity

content/en/getting-started/_index.md
wasn't sure if it's smarter to ref the whole link or just the name directly. so I took my 50% chance and unified them.
=> add service links to getting started guide

content/en/user-guide/state-management/cloud-pods/index.md
This PR relates to [this item in the Notion board](https://www.notion.so/localstack/Update-cloudpods-docs-to-clarify-permissions-3e0bf0af6bda4dfbbdfba8a231d2cd7a?pvs=4), cc @cabeaulac.
In a nutshell, we clarify the current state of the pods' permissions.
Also added some minor improvements.
=> Added notes about pods permissions

content/en/getting-started/auth-token/index.md
In this page's "Managing your License" section: https://docs.localstack.cloud/getting-started/auth-token/, there was a typo in the word "offering," which included an extra 'r.' I have corrected this typo.
=> Fix typo in documentation, closes #1100

content/en/contributing/multi-account-region-testing.md
Localstack now supports multiple accounts and regions compatibility. This document guides the contributors to test their changes against cross accounts and region.
=> add cross accounts and region testing in LS docs

content/en/contributing/multi-account-region-testing.md
This PR changes the type of variable `randomize-aws-credentials` from `string` to `boolean`.
=> change type of variable `randomize-aws-credentials`

content/en/user-guide/state-management/persistence/index.md
Found some minor typos in supported services list for persistence
=> fix: typos in supported services list for persistence page

content/en/contributing/multi-account-region-testing.md
This PR: 
- changes the non AWS validated example of `test_api_gateway_kinesis_integration` to a AWS validated example: `test_apigateway_with_step_function_integration`. 
- changes the example for inter service communication in cross-account using `with_assumed_role(...)`
=> fix the examples in cross accounts guide

layouts/partials/coverage/coverage_table.html, layouts/shortcodes/localstack_coverage_table.html
For the coverage api we still need to adapt the terminology, as we currently use the wording `Edition` and `version` which both should be replaced with `image`. 
* This PR updates the templates we have that are used to create the individual pages
* The changes can be seen in the preview: https://localstack-docs-preview-pr-1159.surge.sh/references/coverage/
=> switch term 'version' with 'image'

content/en/user-guide/ci/circle-ci/index.md
We'd like to provide a drop-in snippet library for the users in circle-ci too.
- Add startup snippet
- Add config section
- Add pro activation part
- Add snippet for log dumping
- Store state variations (workspace, cache, cloud pods, ephemeral instance)
=> New circle ci docs

assets/scss/_styles_project.scss
This PR makes a tiny cosmetic fix to links. Earlier the link anchor on headers had an underline when hovered. This PR removes it.
=> Remove hover underline for headers

content/en/user-guide/aws/transcribe/index.md
https://github.com/localstack/localstack/pull/10629 fixes the issue described in the Transcribe documentation. Therefore, we can remove that note once that fix is merged.
=> Remove note for transcribe on ARM

CODEOWNERS, content/en/user-guide/ci/codebuild/index.md
We'd like to provide a drop-in snippet library for the users in AWS CodeBuild too.
- Add startup snippet
- Add config section
- Add pro activation part
- Add snippet for log dumping
- Store state variations (workspace, cache, cloud pods, ephemeral instance)
- Known issues and limitations section
- CI CODEOWNERS
=> Codebuild snippet library

content/en/contributing/multi-account-region-testing.md
The branches of forks are not directly visible in CircleCI.
This can be confusing if you want to run the MA/MR pipeline for community contributions like https://github.com/localstack/localstack/pull/10625.
This PR adds a short explanation on how to trigger pipelines for PRs coming from forks.
- Adds a very small section to explain that for PRs coming from community contributions (forked repositories), the PR number can be used.
- [CircleCI Docs](https://support.circleci.com/hc/en-us/articles/360049841151-Trigger-Pipelines-on-Forked-Pull-Requests-with-CircleCI-API-v2)
- Tested in our community project's branch selection.
=> add MA / MR pipeline docs for PRs coming from forks

content/en/user-guide/aws/ecs/index.md
We recently integrated live log streaming from ECS containers to CloudWatch, rather than dumping the logs at the end of the task (which may never happen normally for services). We should highlight this feature as it improves parity, as well as developer experience.
- Add log configuration to the example task definition
- Highlight that logs should be available
- Show example of fetching container logs
=> Update ECS quickstart to demonstrate CloudWatch Logs integration

content/en/contributing/development-environment-setup.md
We are currently missing a description of how what extra dependencies are required for running in host mode. This PR provides initial instructions and improves the dev setup guide.
As suggested by @alexrashed in a review comment [here](https://github.com/localstack/localstack/pull/10615#discussion_r1562444858).
=> Clarify dev dependencies for host mode

layouts/404.html
This PR removes a Hugo help note from the 404 page.
---
=> Update 404 page

Makefile, content/en/references/configuration.md, content/en/user-guide/aws/feature-coverage.md
Add config docs for the new opt-in Java-based event ruler introduced in https://github.com/localstack/localstack/pull/10615
https://localstack-docs-preview-pr-1189.surge.sh/references/configuration/#miscellaneous
I added it under "Miscellaneous" because it is not specific to a certain service and not really global for entire "Core" neither.
=> Add event ruler config

content/en/user-guide/aws/appsync/index.md, content/en/user-guide/aws/feature-coverage.md
LocalStack v3.4 adds evaluation endpoints for AppSync resolvers. This PR documents that with examples and links to AWS documentation.
=> Add documentation for evaluation endpoints

content/en/references/configuration.md
The behavior caused confusion in some customers.
=> Clarify auto-load-pod and persistence

content/en/user-guide/aws/opensearch/index.md
We have seen some requests in the past on how to connect OpenSearch Dashboards to OpenSearch domains provisioned in LocalStack. This PR adds a short guide on how to do that.
Happy for any feedback!
=> add instructions on how to connect opensearch dashboards

content/en/user-guide/aws/lambda/index.md
There's already a warning in the Localstack logs but you only really see this after trying it and might also just easily glance over it. @HarshCasper noted that we might therefore want to also add this to the lambda service documentation.
=> Add note about Lambda response streaming not being implemented yet

content/en/references/configuration.md
I've been setting up my localstack S3 and couldn't get the signature validation passing.
I came across [this comment](https://github.com/localstack/localstack/issues/9538#issuecomment-1792255886) which indicated I needed to set my access key/secret key to the specific value of `test` in order to make this work; this PR adds that note to the configuration information for S3.
I had been trying to use a structured S3 key, like referenced [in the docs](https://docs.localstack.cloud/references/credentials/#structured-access-key-id)
I had thought this might be related to me running the `s3-latest` docker image which presumably doesn't include STS, but swapping to the full image doesn't seem to fix it, even when specifying `SERVICES=s3,sts`
=> Specify that S3 signature validation needs the accesskey/secretkey to be set to `test`

content/en/contributing/integration-tests.md
The current flow looks a bit different than what the integration tests documentation refers to (access keys need to be created after user creation), so I tried to reflect that.
=> Update integration-tests.md to match current IAM sandbox user creation flow

content/en/user-guide/aws/pipes/index.md
The Pipes docs miss some feature overview and the limitations need to be updated. Noticed in a customer call today.
* Add enrichments and log destinations to feature overview
* Update and clarify limitations
https://localstack-docs-preview-pr-1247.surge.sh/user-guide/aws/pipes/
=> Add pipes feature overview for enrichments and log destinations

content/en/references/internal-endpoints.md
Add missing internal Lambda endpoint.
PS: This list is hard to maintain moving forward. If we start using internal endpoints more extensively, we might need to consider auto-generating those in the future. They are all missing the HTTP verb (e.g., GET, POST)
=> Add Lambda runtime internal endpoint

content/en/references/internal-endpoints.md
https://github.com/localstack/docs/pull/1250 broke the CI build and this PR fixes it.
I cannot reproduce the issue locally. This might be caused by some outdated Hugo version behaving weirdly with presumably ambiguous references. See commit history of failing build in CI (which all success locally with Golang 1.22.2 and Hugo v0.124.1).
@HarshCasper The Golang ([1.17](https://go.dev/doc/devel/release#go1.17) was deprecated 2022-08-01) and Hugo version ([0.101.0](https://github.com/gohugoio/hugo/releases/tag/v0.101.0) is from Jun 16, 2022) of the docs CI are quite outdated. Consider updating to some more recent version for a better local dev experience because I'm getting more and more such weird issues and deprecation warnings.
Now the Lambda direct link works using the full ref path …
=> Fix ambiguous ref in CI build

content/en/references/changelog.md, content/en/references/configuration.md, content/en/user-guide/aws/events/index.md, content/en/user-guide/aws/lambda/index.md, content/en/user-guide/aws/pipes/index.md, content/en/user-guide/ci/circle-ci/index.md, content/en/user-guide/ci/codebuild/index.md, content/en/user-guide/ci/github-actions/index.md, content/en/user-guide/ci/gitlab-ci/index.md, content/en/user-guide/cloud-sandbox/_index.md, content/en/user-guide/cloud-sandbox/application-previews/index.md, content/en/user-guide/cloud-sandbox/ephemeral-instance/index.md, content/en/user-guide/extensions/_index.md, content/en/user-guide/extensions/managing-extensions/index.md, content/en/user-guide/state-management/export-import-state/index.md, content/en/user-guide/state-management/pods-cli/index.md, content/en/user-guide/web-application/ci-analytics/index.md
Migrate to the unified **preview** and **experimental** terminology following our internal decision doc "Communicate maturity levels of features under development".
* Add terminology explanation "Features under Development" under the Changelog docs
* Add a comment about semver and AWS parity under the Changelog docs
* Migrate beta => preview
* Migrate alpha => experimental (didn't find any occurrences)
* Change the event ruler from experimental to preview stage. Given the thorough test coverage and positive customer feedback, we can consider this well-enough tested to advertise more broadly.
=> Unify terminology for features under development

content/en/user-guide/aws/ecr/index.md
Per default, ECR repositories are now served over the edge proxy (since `ECR_ENDPOINT_STRATEGY=domain` is the default).
This leads to different endpoint uris.
To avoid confusion, we should update those endpoints.
* Update endpoint uris to new format
Thanks @silv-io for the hint!
=> Update ECR repository uris to the new default endpoint format

content/en/user-guide/aws/cloudformation/index.md
This PR documents:
- Support for AWS::WAFv2::WebACL
- Support for AWS::WAFv2::WebACLAssociation
- Support for AWS::WAFv2::IPSet
- Support for AWS::WAFv2::LoggingConfiguration
=> add docs on wafv2 cfn provider

content/en/user-guide/lambda-tools/hot-reloading/index.md
With localstack/localstack#10857, we introduced an option to use placeholders for environment variables in hot reloading paths for lambda.
This allows the users to reuse their IaC templates or CloudPods between different machines, if there is a common point on the filesystem to there are relative paths to the code directories.
* This PR adds documentation on that functionality, and an example how to use these placeholders.
=> Add documentation for lambda hot reloading placeholders

content/en/user-guide/aws/sts/index.md, data/persistence/coverage.json, scripts/persistence/create_persistence_docs.py, scripts/persistence/notion/catalog.py
As suggested by @HarshCasper, this PR introduces the possibility of excluding services from the automatic generation of the persistence docs.
There is now a checkbox field in Notion called "exclude from docs" that one can check.
This PR also rerun the generation script to the latest updates of the Notion catalog.
=> Exclude services from the persistence docs

content/en/user-guide/lambda-tools/hot-reloading/index.md
It appears there's some confusion regarding the setting of the S3Key path in the documentation, which complicates the use of hot-reloading.
I have modified it to improve visibility, emphasizing the necessity of using an absolute path. 
Perhaps we should also clarify that it must be the path of the host machine.
- The PWD command has been omitted, as it pertains only to macOS.
- The TOC has been removed from the article itself (they can be found on the right side of the website).
- Some formatting issues have been corrected.
=> Fix hot reloading s3 path

content/en/user-guide/state-management/cloud-pods/index.md
It happened a couple of times that customers could not work with s3 remotes on older CLI versions (mostly the `load` and `list` commands were targeting our platform instead). Since updating the CLI was an easy fix, I added a callout in the docs.
=> add notes on CLI version for s3 remote

content/en/user-guide/aws/dms/index.md, scripts/create_data_coverage.py
=> add dms docs

data/coverage/service_display_name.json, scripts/create_data_coverage.py
* Remove skipping of DMS from the coverage creation script
* add DMS details to the `data/coverage/service_display_name.json`
Verified that DMS docs are created in https://github.com/localstack/docs/pull/1290 (running workflow against the branch)
* https://localstack-docs-preview-pr-1290.surge.sh/references/coverage/coverage_dms/
**The workflow will be re-run on main after the merge.**
=> prepare coverage docs creation for DMS

content/en/user-guide/aws/lambda/index.md
This PR updates the Lambda Layer documentation by:
- Clarifying that the feature is available and functional with the Pro image.
- Indicating that Layers can be referenced but are not used in the Community image.
This resolves a recent customer issue where there was confusion about Lambda Layer support in the Pro image. /cc: @komarkovich
=> fix lambda layer documentation

content/en/user-guide/web-application/instance-management/index.md
This PR documents how to bind to a custom IP address and port, addressing a problem some recent customers have faced.
=> add docs on binding to custom ip address & port

content/en/getting-started/installation.md, content/en/references/configuration.md
Our getting started example does not mount the Docker socket. If the user does this, they get lots of log messages regarding failed connections to the Docker socket (inside the container). This is off-putting for a new user.
* Show mounting the Docker socket into the LocalStack container for the Docker installation section
* Expose ports on 127.0.0.1 by default
* Make more complete examples for Docker and Docker Compose
* Add info about `LOCALSTACK_` prefix for config variables in configuration reference
* Improve wording around why we mount the Docker socket
=> Mount docker socket in installation example

content/en/getting-started/quickstart/index.md
`jq` needs JSON output to parse the configuration. This fixes the used commands
=> Fix arguments passed to awslocal

content/en/user-guide/lambda-tools/hot-reloading/index.md
This PR:
- Uses tabpane and tab header to put all examples together 
- Make the documentation consistent for all examples together
Preview: https://localstack-docs-preview-pr-1304.surge.sh/user-guide/lambda-tools/hot-reloading/#deployment-configuration-examples
=> add Deployment Configuration Examples in tab panes

content/en/tutorials/ephemeral-application-previews/index.md, content/en/user-guide/ci/codebuild/index.md, content/en/user-guide/ci/github-actions/index.md, content/en/user-guide/cloud-sandbox/application-previews/index.md
- we plan to actively maintain setup-localstack, so pinning it to the main branch can result in broken snippets
- simplified workflows in snippet libraries with new action
- push forward cloud pods and ephemeral instances to promote them as preferred state management options
=> Update GHA versions

scripts/create_data_coverage.py
Some API coverage details contained the same test (including the same response code) in the list of tests.
This PR fixes this, by not adding duplicated information to the test-details.
=> skip duplicated test details for api coverage

content/en/user-guide/aws/kinesisanalytics/index.md
Preview: https://localstack-docs-preview-pr-1324.surge.sh/user-guide/aws/kinesisanalytics/
=> revamp kinesis analytics docs

content/en/user-guide/tools/dns-server/index.md
With 3.5, the LocalStack CLI won't try to publish port 53 on the host anymore by default.
However, there is a new flag `--host-dns`, which will instruct the CLI to publish it.
This PR adds this information to the DNS server documentation page.
* Document new behavior for the DNS port publishing of the CLI. Instead of publishing automatically, you now have to provide a flag
=> Document new CLI flag `--host-dns` for exposing port 53 to the host

content/en/references/configuration.md, content/en/user-guide/aws/cloudformation/index.md
- Add callout to warn users that with 3.5 there's a new default resource deployment engine that more accurately orders resources by their dependencies.  See https://github.com/localstack/localstack/pull/10849
- Add config option to revert to the old behavior
- (explicitly mentioned that this is only available temporarily because we don't wan't to commit to keeping this alive for long.
=> Add note to CFn service page about the new default deployment engine

content/en/user-guide/aws/ec2/index.md, layouts/shortcodes/callout.html
@Anze1508 made me aware that the EC2 link from the callout to the "Create a key pair" anchor wrongly leads to "/#create-a-key-pair" instead of "#create-a-key-pair"
- Fix the links by directly referencing the anchor on the EC2 page using the `relref` shortcode.
This is just a workaround, it would be great if anchor links would work in the `callout` shortcode introduced by @viren-nadkarni.
Unfortunately this is actually a bug in the `alert` shortcode of docsy (of which the `callout` shortcode is a fork of).
=> fix EC2 create-a-key-pair anchor links

layouts/partials/developer-hub/application.html, layouts/partials/footer.html, layouts/partials/sidebar-tree.html, layouts/tutorials/single.html
While looking into another small issue, I stumbled upon an issue in the mobile rendering: The navigation bar is not working correctly: [Screencast](https://github.com/localstack/docs/assets/2796604/702d174f-a8ef-49a0-a2e9-752fd1b1bf62)
As it turns out that this was missed in our overwritten layout files during the upgrade of docsy to v0.10 which came with an upgrade to Bootstrap 5: https://github.com/localstack/docs/pull/1268
Bootstrap 5 introduced a breaking change by renaming `data-toggle` to `data-bs-toggle`: https://getbootstrap.com/docs/5.0/migration/#javascript
It seems like this might be an issue for other people as well: https://github.com/localstack/docs/pull/1336
- Migrates usages of `data-toggle` to `data-bs-toggle`.
- We can test in the preview deployment that his fixes:
- The …
=> fix bootstrap 5 upgrade issues

scripts/get_latest_github_metrics.sh
Since some changes in our core repositories happened, where the parity calculations don't happen on every commit, we're running into issues with the parity update script (see https://github.com/localstack/docs/actions/runs/9639842836). Now the parity reporting is always to be found in the latest scheduled run or manual full run of the pipelines.
- Remove old handling of not found artifacts which relied on finding it on other executions on the same tree. The assumption that parity metrics are always in the latest commits or on the tree of dependent branches does not hold anymore. 
- Add loop based handling where the last 20 runs on `master` are looped through and searched for the artifact
Running it locally now yields following result:
```
Searching for Artifact: parity-metric-ext-raw-* in …
```
=> Fix parity update script

content/en/references/configuration.md, content/en/user-guide/aws/lambda/index.md
With the recent changes in Lambda RIE log levels (https://github.com/localstack/localstack/pull/11067), we should describe the option of how to configure log levels clearly (e.g., if support needs to ask for more detailed logs).
Preview: https://localstack-docs-preview-pr-1339.surge.sh/user-guide/aws/lambda/#localstack-lambda-runtime-interface-emulator-rie
* Add a section to describe the Lambda RIE / Init binary with some config options using a disclaimer regarding API stability (considering it internal API for now)
* Fix Lambda config ordering (alphabetically)
* What's the best name?
* Runtime Interface Emulator (RIE)
* LocalStack Runtime Interface Emulator (LRIE)
* Lambda init binary
* Lambda runtime init
* ...
* The section title …
=> Describe Lambda RIE / init config

content/en/references/configuration.md
@robertlcx mentioned that the configuration reference is currently missing `EXTENSION_AUTO_INSTALL`.
This PR adds this env var to the config reference.
- Adds `EXTENSION_AUTO_INSTALL` to "Miscellaneous" in the config reference and links to the detailed description of the feature.
=> add EXTENSION_AUTO_INSTALL to config reference

content/en/getting-started/installation.md, layouts/shortcodes/cli-binary-download.html
This PR makes the following changes to the 'Installation' page:
- Several formatting, spacing and padding fixes
- Removes the `Alternative: Python` section from each platform in favour of the dedicated pane. This removes a lot of duplicated documentation.
- Reorders tabs as: Linux, Mac OS, Windows, Other. This is partly motivated by [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) and by assumed OS installbase.
=> Update Installation page

content/en/user-guide/integrations/sdks/go/index.md
Upon [upgrading the v2 aws sdk dependency](https://github.com/dorklyorg/dorkly/commit/3a212cea2099d504ba73c43c678e4bce668a9d9f) I noticed some deprecation warnings. 
Removes deprecated usages of EndpointResolver in favor of specifying BaseEndpoint. 
This change 'works for me' (my test passes) but could use some additional verification for those with different use cases.
See aws docs: https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/#mutable-endpoint
=> Update golang s3 example to avoid using deprecated bits

content/en/tutorials/elb-load-balancing/index.md, content/en/tutorials/ephemeral-application-previews/index.md, content/en/tutorials/gitlab_ci_testcontainers/index.md, content/en/tutorials/java-notification-app/index.md, content/en/tutorials/replicate-aws-resources-localstack-extension/index.md, content/en/tutorials/schema-evolution-glue-msk/index.md, content/en/tutorials/simulating-outages-in-your-application-stack/index.md, data/developerhub/services.json
There was inconsistent naming of the services and platforms that were used to generate the filters. This fixes that and removes the duplicate filters on the sidebar.
=> Fix labels for filters

content/en/user-guide/ci/codebuild/index.md, content/en/user-guide/ci/github-actions/index.md, content/en/user-guide/cloud-sandbox/application-previews/index.md
Bumping `setup-localstack` version across docs
=> bump setup-localstack version

content/en/references/configuration.md, content/en/user-guide/aws/mwaa/index.md
> [!CAUTION]
MWAA now behaves similar to AWS when checking S3 bucket for updates. Earlier MWAA acted on the updates synchronously eg. a DAG would be registered in Airflow immediately after uploading to S3.
Now updates are done in batches every 30 seconds. The update frequency can be adjusted with config option `MWAA_S3_POLL_INTERVAL`.
https://docs.aws.amazon.com/mwaa/latest/userguide/configuring-dag-folder.html#configuring-dag-folder-how
=> MWAA: Add MWAA_S3_POLL_INTERVAL config option

content/en/user-guide/aws/dms/index.md
Add support for s3 as a source in DMS.
=> dms: add support for s3 source

.github/workflows/docs-parity-updates.yml
We just recently adjusted some of our workflow names by introducing a prefix (`AWS / ...`).
This unfortunately broke the parity update workflow because it directly references the workflow by its name, [see this run](https://github.com/localstack/docs/actions/runs/10034961759).
This PR fixes this issue.
- Adjust the workflow name for our pro parity metrics download.
=> fix parity update action

content/en/user-guide/aws/dynamodb/index.md
I found that the endpoint URL for DynamoDB TTL has a wrong double slash `//`. I fixed it to single slash `/`.
Other document (e.g., for [SNS](https://github.com/search?q=repo%3Alocalstack%2Fdocs+%22localhost%3A4566%2F_aws%2F%22&type=code)) also uses the format `localhost:4566/_aws/`.
It worked good on my sandbox environment😀
```sh
$ curl -X DELETE localhost:4566/_aws/dynamodb/expired
{"ExpiredItems": 1}%
```
Thanks!
=> Fix endpoint url correctly for DynamoDB TTL

content/en/user-guide/ci/gitlab-ci/index.md
Add link to the tutorial with a demo project in the GitLab CI documentation page
=> add example reference to gitlab documentation page

content/en/user-guide/extensions/managing-extensions/index.md
Documents https://github.com/localstack/localstack/issues/11221
=> add a troubleshoot note for extensions

content/en/user-guide/aws/sagemaker/index.md
This PR adds a short notice about how GPU models are not supported in SageMaker
=> Add SageMaker limitation notice about GPU models

scripts/get_latest_circleci_metrics.sh
We recently had a few changes to our pipelines.
https://github.com/localstack/docs/pull/1342 already adjusted the Parity Update scripts to some of the changes.
Unfortunately, we've overlooked one change: The pipeline in CircleCI in `localstack/localstack` has been changed such that it is not called `main` anymore: https://github.com/localstack/localstack/pull/11049 renamed `main` to `full-run` and introduced a new `acceptance-only-run`.
Unfortunately, we haven't realized that this would have to change this here as well.
Now the artifacts of the old pipeline are not available anymore, which is why the run failed: https://github.com/localstack/docs/actions/runs/10242910192
- This PR fixes the parity update action by referencing the correct workflow again.
- [Triggered a run from this …
=> fix parity upgrade action by updating CircleCI URL

content/en/user-guide/aws/lambda/index.md
- Update docs to reflect supporting including an `alias` in custom URL subdomains when using predictable Lambda URLs.
- NB: should be merged in following https://github.com/localstack/localstack/pull/11272
- Split up the single `callout` into two seperate `callouts` in Create a Lambda function` and  `Create a Function URL`.
- `### Create a Lambda function` contains docs on tagging when creating a new Lambda Function.
- `### Create a Function URL` contains information on expected behaviour when creating new URLs for tagged custom tagged functions.
=> Lambda: Include support for custom URL aliases

content/en/user-guide/tools/transparent-endpoint-injection/index.md
Our documentation of Transparent Endpoint Injection does not cover:
* that it's implicitly disabled with the `DNS_ADDRESS=0` configuration, which is common in old examples, and still very present in users' configurations
* that it's required for e.g. CDK custom resources to function
* actually if the lambda uses an SDK that supports `AWS_ENDPOINT_URL` then we don't technically need TEI, however
* we also disable the required TLS verification when `DNS_ADDRESS=0'`.
[Rendered](https://localstack-docs-preview-pr-1419.surge.sh/user-guide/tools/transparent-endpoint-injection/)
=> Add callouts for DNS configuration of TEI

.markdownlint-cli2.yaml, content/en/references/coverage/_index.md
Seems to be introduced with [setup markdown linting PR](https://github.com/localstack/docs/commit/f2ebb421e1f03d42e0a1cd15cf4710a47914c9f1#diff-5c923b2fd3b4f3f6029bf1a18d7e2efe9e4f63be8ced065c63aaaa909f50fcfa)
fixes https://github.com/localstack/docs/issues/1429
=> fix search script

content/en/user-guide/aws/apigateway/index.md, content/en/user-guide/aws/feature-coverage.md
This PR updates the documentation around API Gateway Custom Domains. The feature was not marked as Pro only. Also added a small paragraph showing the use of it.
\cc @thrau 
Page preview: https://localstack-docs-preview-pr-1440.surge.sh/user-guide/aws/apigateway/#custom-domain-names-with-api-gateway-pro
=> update APIGW docs on custom domain

content/en/user-guide/aws/pca/index.md
> [!CAUTION]
This PR extends ACM-PCA docs with details steps to
- Set up and configure a hosted CA
- Issue end-entity certificates
=> ACM-PCA: Add docs to set up CA and issue certs

content/en/references/configuration.md, content/en/user-guide/aws/eks/index.md
We are currently making some changes, to replace the implicit switch between the `k3s` and `local` EKS K8S providers, which lead to a lot of confusion.
In the future, the switch is made purely by the `EKS_K8S_PROVIDER` configuration variable, the mounting of a kubeconfig alone will no longer suffice to switch to the `local` provider.
Also, we stop automatically mounting the kube config at `~/.kube/config` from the host into the container.
* Document the new `EKS_K8S_PROVIDER` config variable
* Document the flag in the local provider documentation, and clarify how to mount the kubeconfig in the LocalStack container from now on
* Document requirement for X509 certificate authentication to the local cluster.
=> Document new EKS_K8S_PROVIDER configuration

content/en/references/configuration.md
We introduced a flag for the user to control the version of the JS libs version to use with AppSync JavaScript resolvers. We never documented this feature beyond some support issues. This PR outlines how the flag works.
=> AppSync: document flag for specifying JS libs version

content/en/references/configuration.md
With https://github.com/localstack/localstack/pull/11414 we removed the legacy fallback option for CloudFormation deploy implementation. This PR removes the documentation for that flag.
* Remove documentation for `CFN_LEGACY_TEMPLATE_DEPLOYER` documentation
=> CFn: remove CFN_LEGACY_TEMPLATE_DEPLOYER flag option

content/en/user-guide/aws/eks/index.md
The current commands for configuring the [ingress](https://docs.localstack.cloud/user-guide/aws/eks/#configuring-an-ingress-for-your-services) in the EKS documentation don't have the proper indentation:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
name: nginx
spec:
selector:
app: fancier-nginx
ports:
- name: http
protocol: TCP
port: 80
targetPort: 80
EOF
```
```
cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: nginx
annotations:
ingress.kubernetes.io/ssl-redirect: "false"
spec:
rules:
- http:
paths:
- path: /test123
pathType: Prefix
backend:
service:
name: nginx
port:
number: 80
EOF
```
When running it I receive the following message error:
> error: error parsing STDIN: error converting YAML to JSON: yaml: line 8: …
=> Correcting commands in Ingress configuration from EKS docs.

content/en/user-guide/aws/batch/index.md
Recently, we implemented parameter substitution to Batch. As [AWS](https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#parameters) have its own way to do this, I believe the docs should illustrate how to configure parameter substitution to set default values.
=> Adding parameter substitution implementation example to Batch docs

config.toml
We just released [3.7.2](https://github.com/localstack/localstack/releases/tag/v3.7.2). This PR updates the version in the docs (to update the download links and version mentions).
=> Update latest version to 3.7.2

content/en/references/configuration.md, content/en/user-guide/aws/iam/index.md, content/en/user-guide/security-testing/iam-enforcement/index.md
This PR:
- Adds pro tags to IAM config options (such as `ENFORCE_IAM` etc.) 
- Adds a section on IAM Special Tools (IAM Policy Stream, IAM Enforcement, etc.) 
- Links IAM feature coverage to IAM Enforcement doc
=> Revamp IAM docs

content/en/user-guide/integrations/gitpod/index.md
Proper casing for `Gitpod` in [relevant integration docs](https://docs.localstack.cloud/user-guide/integrations/gitpod/).
=> Typos in Gitpod integration docs

content/en/user-guide/aws/cognito/index.md
I believe the Lambda Trigger section in Cognito's documentation would be more illustrative if it included a Lambda function example demonstrating how to migrate a user on authentication.
=> Adding code example to Cognito Lambda trigger documentation.

content/en/user-guide/aws/elasticache/index.md
Small fix. The url to the API coverage is not properly set:
=> Correcting format for Api coverage url

content/en/user-guide/aws/kms/index.md
In the previous documentation, it was possible to create a key, but when running `kms encrypt`, the error `Invalid key size (136) for AES.` would occur. I've updated the documentation to ensure that the key is generated with a size of 32 bytes.
Example:
```bash
$ echo 'c3VwZXIgc2VjcmV0IGtleQo=' | base64 -d
super secret key
$ awslocal kms create-key --tags '[{"TagKey":"_custom_key_material_","TagValue":"c3VwZXIgc2VjcmV0IGtleQo="}]'
{
"KeyMetadata": {
"AWSAccountId": "000000000000",
"KeyId": "74a102af-5a49-40bb-bac6-530e7c0cb9cd",
"Arn": "arn:aws:kms:ap-northeast-1:000000000000:key/74a102af-5a49-40bb-bac6-530e7c0cb9cd",
"CreationDate": "2024-09-14T14:37:48.238508+09:00",
"Enabled": true,
"Description": "",
"KeyUsage": "ENCRYPT_DECRYPT",
"KeyState": "Enabled",
"Origin": "AWS_KMS", …
```
=> KMS: Fix method for specifying custom key material

content/en/user-guide/aws/ec2/index.md
1. I have added a way to set the correct file permissions for the `key.pem` file. Using the SSH connection on a Windows system requires this.
For more information, refer to the [documentation](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-acl?view=powershell-7.4) for the `Set-Acl` command.
Additionally, there is an alternative method.
```powershell
icacls.exe key.pem /reset 
icacls.exe key.pem /grant:r "$($env:username):(r)"
icacls.exe key.pem /inheritance:r
```
For more information, refer to the [documentation ](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/icacls)for the `icacls` command.
I prefer to use the PowerShell version, but we can change it.
3. Updated the AMI to use a new version of Ubuntu that uses ssh …
=> Update permissions for key pair file in EC2 documentation

content/en/user-guide/aws/pca/index.md
Fixes a command that is attempting to append (>) to `tee` rather than pipe (|) to `tee`
=> Update command in ACM-PCA user-guide

content/en/user-guide/aws/elasticache/index.md, content/en/user-guide/aws/iam/index.md, content/en/user-guide/security-testing/iam-enforcement/index.md
With recent PRs #1496 and #1490 we introduced some hard-coded links as bandages for link errors.
However, we should try to resort to ref shortcodes if possible.
* Change links back to use the ref shortcode
=> Fix hardcoded links and replace them with references

content/en/user-guide/integrations/pulumi/index.md
`pulumi-local` currently does not support the `aws-native` package, but this is not mentioned anywhere in the docs.
- add callout into Pulumi docs
=> docs(pulumi): Add callout on aws-native package in pulumi-local

content/en/references/configuration.md, content/en/user-guide/aws/apigateway/index.md
This PR adds documentation about the NextGen API provider. Community provider work can be seen here: https://github.com/localstack/localstack/pull/11035
=> add APIGW NextGen doc

content/en/user-guide/lambda-tools/hot-reloading/index.md
When using Lambda Hot Reloading in Docker distributions that are not Docker Desktop, the code is not updated. There have been a few issues related to this matter.
I believe this should be documented, as it would help troubleshoot similar issues related to this behaviour more quickly.
Based on the following [Github issue](https://github.com/localstack/localstack/issues/11415#issuecomment-2341140998) I added a note on the Lambda Hot Reloading documentation on how to set up LS to use Hot Reloading in Rancher Desktop and Colima environments.
=> Lambda Hot Reloading not updating function when not using Docker desktop

content/en/user-guide/aws/redshift/index.md
Add note about the difference in LocalStack editions for RedShift service.
=> Add note about LocalStack editions

content/en/references/internal-endpoints.md
We recently introduced Swagger UI served directly via LocalStack, documenting all our internal endpoints.
We add this link to the docs and remove the manually-written list of endpoints contained in this page.
=> add reference to the swagger UI

content/en/getting-started/installation.md
The attribute `version` is obsolete and will be ignored when running the docker compose configuration.
=> Removing version attribute from docker compose config

content/en/references/configuration.md, content/en/user-guide/aws/bedrock/index.md
This PR will be running alongside the implementation work
=> Add Bedrock service documentation

content/en/user-guide/lambda-tools/debugging/index.md
Attempt to improve the visibility on the remote debugging page.
=> Add note on debugging limitations for Lambda functions

content/en/user-guide/aws/ec2/index.md
> [!NOTE]
> This change targets the LocalStack v4.0 release
This was deprecated in v3.2
=> EC2: Drop deprecated AMI

content/en/user-guide/aws/rds/index.md
From @viren-nadkarni's PR:
> AWS dropped RDS PostgreSQL 10 support on 17 April 2023.
> https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.DBVersions.html#PostgreSQL.Concepts.General.DBVersions.Deprecation10
> LocalStack deprecated this in v3.2.0.
This PR removes any references to PostgreSQL 10
=> drop references to postgresql 10 from rds

content/en/user-guide/aws/cloudformation/index.md
We removed the legacy fallback of the template deployer with LocalStack version 3.6 so we should not mention this option in the docs.
=> Remove callout about legacy CFn template deployer

content/en/tutorials/ephemeral-application-previews/index.md
GitHub is currently phasing out support for `actions/upload-artifact` versions other than the latest major release v4: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
This PR updates the references to use the new version of the action.
Update the docs to reference the latest version of `actions/upload-artifact`.
=> update docs to reference to actions/upload-artifact@v4

content/en/user-guide/aws/fis/index.md
> [!NOTE]
> This change targets the LocalStack v4.0 release
This was deprecated in v3.6
=> FIS: Drop support for LocalStack-only actions

content/en/getting-started/quickstart/index.md
Deploy script was moved in https://github.com/localstack-samples/sample-serverless-image-resizer-s3-lambda/pull/37
=> Update deploy script path in quickstart guide

content/en/references/configuration.md, content/en/user-guide/aws/lambda/index.md
Documentation updates for removing ESM v1 https://github.com/localstack/localstack/pull/11733
=> Remove Lambda ESM v1 feature flag

content/en/references/configuration.md
Remove configuration related to legacy stepfunctions provider: https://github.com/localstack/localstack/pull/11734
The service page for stepfunctions doesn't mention the legacy provider anymore.
=> Remove legacy stepfunctions provider

content/en/references/configuration.md, content/en/user-guide/aws/bedrock/index.md
This PR updates the documentation to cover the new LLM-enabled functionality of Bedrock and the new configuration variables.
=> Update bedrock v4 docs

content/en/references/configuration.md
In https://docs.localstack.cloud/user-guide/localstack-enterprise/kubernetes-executor/, we can already see that kubernetes features are limited to LocalStack enterprise.
However, the (pro) in the configuration page could still confuse users as to the licensing of the lambda kubernetes executor.
* Change references to the license of the lambda kubernetes executor to `enterprise` on the configuration page
=> Clarify license of lambda kubernetes executor in the configuration page

content/en/references/configuration.md, content/en/user-guide/aws/bedrock/index.md
Changing the default model for Bedrock (see https://github.com/localstack/localstack-ext/pull/3747)
=> Update Bedrock docs for v4

content/en/references/credentials.md, content/en/references/init-hooks.md
> [!NOTE]
This PR updates the docs mentioning that init hooks should use explicit AWS credentials.
=> Require credentials in init hooks

content/en/references/configuration.md
PR following https://github.com/localstack/localstack/pull/11930
This documents the `SNS_SES_SENDER_ADDRESS` config variable to be able to change the sender address of SNS email notifications. 
I would also like to talk about it in the service page (SNS), but I'm not seeing how and where to add it..?
=> add configurable variable for SNS email sender

content/en/references/configuration.md, content/en/user-guide/aws/bedrock/index.md
In line with upcoming stability improvements for Bedrock, this PR changes the default model in the docs to `smollm2`.
Additionally, a troubleshooting section is added describing the issue of insufficient storage or memory space in Docker Desktop.
=> Add troubleshooting section to Bedrock and adapt default model

content/en/user-guide/aws/firehose/index.md, content/en/user-guide/aws/kinesisanalytics/index.md, content/en/user-guide/aws/kinesisanalyticsv2/index.md
> [!NOTE]
This PR adds docs for the new emulated AWS service: Managed Service for Apache Flink
=> Docs for Managed Service for Apache Flink

content/en/user-guide/aws/cognito/index.md
Currently, the client credentials flow is not mentioned in our documentation. This PR adds a brief introduction and a sample on how to set it up.
=> Cognito client crendetials flow

content/en/user-guide/aws/opensearch/index.md
Hi😀
While trying to use OpenSearch Service via LocalStack and referring to the documentation, I encountered some errors.
https://docs.localstack.cloud/user-guide/aws/opensearch/
```sh
$ awslocal opensearch create-domain --cli-input-json file://./opensearch_domain.json --region us-east-1
$ curl -u "admin:really-secure-passwordAa!1" http://secure-domain.us-east-1.opensearch.localhost.localstack.cloud:4566/_cluster/health
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>InternalError</Code><Message>exception while calling s3 with unknown operation: MyHTTPSConnectionPool(host='127.0.0.1', port=53137): Max retries exceeded with url: /_cluster/health (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0xffff65b48110&gt;: Failed to establish a new connection: …
```
=> Fix quotation mark for OpenSearch password

content/en/user-guide/aws/lambda/index.md
Adds a new coverage table for the Lambda event-source mapping section of the docs.
The new table will (approximately) look like:
  |   | SQS |   | Stream |   | Kafka ⭐️ |  
-- | -- | -- | -- | -- | -- | -- | --
Parameter | Description | Standard | FIFO | Kinesis | DynamoDB | Amazon MSK | Self-Managed
BatchSize | Batching events by count. | 🟡 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢
➖ | Batch when ≥ 6 MB limit. | 🟠 | 🟠 | 🟠 | 🟠 | 🟢 | 🟢
MaximumBatchingWindowInSeconds | Batch by Time Window. | 🟠 | ➖ | 🟠 | 🟠 | 🟢 | 🟢
MaximumRetryAttempts | Discard after N retries. | ➖ | ➖ | 🟢 | 🟢 | ➖ | ➖
MaximumRecordAgeInSeconds | Discard records older than time t. | ➖ | ➖ | 🟢 | 🟢 | ➖ | ➖
Enabled | Enabling/Disabling. | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢
FilterCriteria | Filter criteria object. | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢
FunctionResponseTypes | …
=> [ESM] Add table for feature-specific coverage

content/en/tutorials/cloud-pods-collaborative-debugging/index.md, content/en/user-guide/aws/apigateway/index.md
We've got a report by a user trying to access API Gateway `invoke-api` URL that it wouldn't work for them, because they constructed the API URL with Terraform, and used the `stage.id` instead of the `stage.name`. They directly reported looking at the documentation for this.
Updating this page to make this more correct.
=> update APIGW URL contruction to use stageName

content/en/user-guide/aws/elb/index.md
We are working on path-based routing for ELB. **Do not merge this PR until the feature is ready**
When that feature becomes available, this change adds a section in the ELB documentation showing the alternative _path based_ URL structure.
[[rendered](https://localstack-docs-preview-pr-1603.surge.sh/user-guide/aws/elb/#alternative-url-structure)]
=> ELB: add alternative URL structure

content/en/user-guide/aws/lambda/index.md
We don't actually support failure destinations in Kafka as of yet. This PR changes the "implemented" to "not implemented".
=> [ESM] Kafka does not yet support failure destinations

content/en/user-guide/aws/kinesis/index.md
This PR fixes the name for the `kinesis` provider to **Kinesis Data Streams**, how AWS calls it.
<https://docs.aws.amazon.com/streams/latest/dev/introduction.html>
=> Kinesis: Fix name

content/en/user-guide/aws/kinesisanalyticsv2/index.md
> [!NOTE]
This PR adds docs for CloudWatch Logs integration and resource tagging support in Managed Service for Apache Flink.
=> Managed Flink: Tagging support and CloudWatch Logs integration

content/en/user-guide/aws/iot/index.md
> [!NOTE]
LocalStack now supports the IoT 'http' rule action.
<https://docs.aws.amazon.com/iot/latest/developerguide/https-rule-action.html>
=> IoT: HTTP rule action

content/en/references/configuration.md
Added small clarification on configuration of profiles.
In my onboarding experience, the ./localstack/ directory was not created when I was trying profiles out and I spent some minutes getting lost on whether this directory was supposed to get automatically created or not. Which should be if you install localstack via cli.
=> Added small clarification on profiles

content/en/user-guide/aws/lambda/index.md
Implemented in https://github.com/localstack/localstack/pull/12087. This update to docs should be merged after ~~the next minor release~~ the next `latest` pro image is shipped.
=> Add s3 as ESM failure destination for Kinesis and DynamoDB stream sources

content/en/user-guide/integrations/kubernetes/index.md
This PR changes the link for the LocalStack Helm chart from [http://helm.localstack.cloud/](http://helm.localstack.cloud/)(just a placeholder page) to [https://github.com/localstack/helm-charts](https://github.com/localstack/helm-charts).
=> Changed helm chart link to GH repo

content/en/user-guide/integrations/gitpod/index.md
This will remove Gitpod Prebuilds configuration via `.gitpod.yml` which has been deprecated.
See [relevant changelog](https://www.gitpod.io/changelog/simplified-prebuilds-defaults), [relevant docs](https://www.gitpod.io/docs/configure/repositories/prebuilds#configuring-prebuilds), and [deprecated docs](https://www.gitpod.io/docs/integrations/github-gitpod-yaml).
=> Remove deprecated configuration for Gitpod prebuilds

content/en/user-guide/integrations/serverless-framework/index.md
Since late October 2024 the serverless-plugin is confirmed to be compatible with Serverless v4. Wondering if there something else we could do more than just removing the warning.
=> remove warning against serverless v4

content/en/user-guide/ci/codebuild/index.md
A user was trying to use LocalStack on CodeBuild, however they kept getting "connection refused" when trying to connect. The solution to their problem was to run their job in "privileged" mode.
Our guide includes a "Current limitations" section at the _bottom_ of the page, however it is not clear that this is a _requirement_.
* Make the _requirement_ more prominent by adding a callout at the top of the page, and labelling it "Requirement"
=> Increase visibilty of codebuild privileged mode requirement

content/en/tutorials/ecs-ecr-container-app/index.md, layouts/shortcodes/github.html
This pull request addresses issue #870.
Changes included:
- Remove references to `<REPOSITORY_NAME>` and `<STACK_NAME>` in favour of a fixed name.
- Fixes broken CloudFormation link.
- Fix broken Hugo shortcode for `github`.
This PR does not address:
- Copy/pasting long blobs of partial files and then making them fit together is very cumbersome
=> Implement multiple fixes for ECR-ECR tutorial

content/en/references/configuration.md
LocalStack PR: https://github.com/localstack/localstack/pull/12158
Update config documentation with removed legacy config for `EVENT_RULE_ENGINE`
=> Move EVENT_RULE_ENGINE to legacy config

content/en/user-guide/aws/bedrock/index.md
Adding a small note about finding small models in the Ollama library when resources are a problem
=> Add comment on using smaller models in Bedrock when resources are restricted

content/en/references/configuration.md
adds documentation for support of `MWAA_DOCKER_FLAGS`
=> add MWAA_DOCKER_FLAGS

content/en/references/configuration.md, content/en/user-guide/aws/bedrock/index.md
Adding information regarding the newest on-demand model switching feature.
Merge only after the feature is merged
=> Add information for on-demand model switching in Bedrock

content/en/user-guide/aws/ec2/index.md
With the current IP(172.17.0.X), the sample doesn't work. However, if we changed it to 127.0.01 it works as expected.
=> Changing ip from ec2 doc's sample

content/en/user-guide/aws/cloudformation/index.md, content/en/user-guide/aws/ec2/index.md
Duplicated from https://github.com/localstack/docs/pull/1579
We now have initial support for setting `NoEcho` in CFn parameters. This PR adds a callout reminding users not to use them for sensitive information, but otherwise they are availble.
Also: fix a linting error with the EC2 docs introduced in #1546
=> CFn: document NoEcho behaviour

content/en/references/configuration.md, content/en/references/coverage/coverage_kinesisanalyticsv2/index.md, content/en/user-guide/aws/kinesisanalyticsv2/index.md, data/coverage/service_display_name.json, data/persistence/coverage.json
There were still references to this services as Kinesis Data Analytics v2 in the service coverage guide when the proper name is Amazon Managed Service for Apache Flink.  In addition, according to the product team at AWS the correct acronym is MSF and not MSAF.
=> Fix references to Kinesis Data Analytics v2

content/en/getting-started/quickstart/index.md, content/en/user-guide/chaos-engineering/chaos-api/index.md
When playing with our cool Chaos API, me and @vittoriopolverino stumbled upon a small issue when copy-pasting one of the examples. The JSON was invalid because it contained a trailing `,` in the payload. This PR fixes that! 🚀 
- Fix the invalid JSON in the Chaos API docs
- Fixes an unrelated linting error introduced with #1341 /cc @HarshCasper
=> fix typo in chaos example

content/en/getting-started/quickstart/index.md, content/en/user-guide/state-management/cloud-pods/index.md
We have been asked to work on pod auto-load for s3 remotes.
We implemented this feature in [#4041](https://github.com/localstack/localstack-ext/pull/4041).
Similar to the "normal" auto-load, the user needs to mount a `init-pods.d` folder into LS.
```bash
.
├── docker-compose.yml
└── init-pods.d
└── pod-list.txt
```
The folder contains a txt file. Now you are able to specify a remote name by just adding it after the name of the pod.
For instance:
```text
foo-pod 
bar-pod,my-remote
```
`foo-pod` will be loaded from our platform, while `bar-pod` will be downloaded from `my-remote`.
The users need to provide to LS with all the necessary environment variables
**NB**: this approach assumes that the remotes has been already configured with the `localstack pod remote add ...` command.
=> Docs for S3 auto load feature

content/en/user-guide/aws/servicediscovery/index.md
The Fargate task definition was incorrect, and this change is necessary to correct the task definition JSON.
https://localstack-docs-preview-pr-1673.surge.sh/user-guide/aws/servicediscovery/
=> ServiceDiscovery: changed commands for ECS sample app

content/en/getting-started/installation.md, content/en/references/external-ports.md, content/en/references/init-hooks.md, content/en/references/network-troubleshooting/endpoint-url/_index.md, content/en/references/podman.md, content/en/tutorials/java-notification-app/index.md, content/en/tutorials/using-terraform-with-testcontainers-and-localstack/index.md, content/en/user-guide/aws/ecs/index.md, content/en/user-guide/aws/es/index.md, content/en/user-guide/aws/opensearch/index.md, content/en/user-guide/aws/s3/index.md, content/en/user-guide/extensions/managing-extensions/index.md, content/en/user-guide/integrations/devcontainers/index.md, content/en/user-guide/integrations/kafka/docker-compose.yml, content/en/user-guide/integrations/rancher-desktop/index.md, content/en/user-guide/lambda-tools/debugging/index.md, content/en/user-guide/lambda-tools/hot-reloading/index.md, content/en/user-guide/state-management/cloud-pods/index.md, layouts/shortcodes/github.html
Reason for removing the version attributes see localstack/localstack#12354.
Also, hugo now takes the default docker compose files directly from the localstack/localstack repository using the github shortcode.
For this to work, I needed to enable the github shortcode to include the file as-is, without any highlighting, as the highlights are already done in the tab.
Happy to discuss this, if there is a better solution.
* Remove `version` top level attributes from all docker compose examples.
* Get fresh versions of the docker compose examples directly from the LS repository.
=> Remove obsolete version top-level elements from compose examples

.github/issue_templates/docs-bug.yaml, .github/issue_templates/docs.yaml
Docs-specific YAML issue templates capture more detailed and actionable feedback when users report issues in our documentation:
- Clear problem descriptions
- Screenshots & reproduction steps
- Consistency in reporting
=> docs: added docs changes and docs bug issue templates

content/en/user-guide/aws/ssm/index.md
Update SSM docs to reflect current LocalStack behavior.
=> Clarify limitations of SSM SendCommand action

content/en/user-guide/aws/kinesisanalyticsv2/index.md
- Reflect recent changes to how LocalStack runs Flink cluster
- Clarify current parallelism limitations
=> Update Managed Flink docs

content/en/user-guide/tools/aws-replicator/index.md
- given early feedback from customer, providing the aws credentials was confusing. I clearly separated the 2 methods, `aws-cli v2` vs other. And removed the "eval" callout as it just seemed to add confusion and is only available for `aws-cli v2`, and still doesn't provide the region, leading to more confusion.
- added github links for opening new issues and requesting support for new resources
=> improve replicator doc

content/en/user-guide/chaos-engineering/chaos-application-dashboard/index.md, content/en/user-guide/cloud-sandbox/_index.md, content/en/user-guide/cloud-sandbox/application-previews/index.md, content/en/user-guide/cloud-sandbox/ephemeral-instance/index.md, content/en/user-guide/security-testing/iam-policy-stream/index.md, content/en/user-guide/tools/event-studio/index.md, content/en/user-guide/web-application/stack-overview/index.md
Fixes https://github.com/localstack/docs/issues/1710 along with other missing items
=> add preview banners and tags to missing pages

content/en/references/coverage/coverage_codebuild/index.md, content/en/references/coverage/coverage_codedeploy/index.md, content/en/references/coverage/coverage_codepipeline/index.md, content/en/references/coverage/coverage_codestar-connections/index.md
This PR hides CodeX services because are not available at this time.
They were initially hidden in #1683 but restored in #1695.
cc: @HarshCasper please be mindful with future automated PRs.
=> Hide CodeBuild, CodeDeploy, CodePipeline & CodeConnections coverage pages

.github/workflows/docs-replicator-updates.yml
adds a workflow to create automatic updates for the replicator resources coverage.
Successful run: https://github.com/localstack/docs/actions/runs/14226716129/job/39867880081
PR Created: #1723
=> Automate replicator coverage

.github/dependabot.yml, CODEOWNERS
This PR removes myself from the CODEOWNERS file of this repo (not on services though), and removes some old outdated entries. It also updates the dependabot config to add @HarshCasper and @quetzalliwrites as reviewers instead.
=> Update CODEOWNERS and dependabot config

content/en/user-guide/aws/cloudfront/index.md
Joel pointed out [one statement](https://github.com/localstack/docs/pull/1752/files#r2077027819) around Lambda@Edge limitation is not correct, and suggested this improved phrasing.
=> Fix doc on Lambda@Edge limitation

content/en/references/api-key.md
Fix grammar typo in _Common activation issues_. Ticket [here](https://www.notion.so/localstack/docs-bug-typo-on-activation-issue-1edfc2a2343180108bc2f27edcd98bc5).
=> Fix typo on activation issue

content/en/references/licensing.md
Update line item in both tables for K8 Pack
“Kubernetes Pack ([K8s](https://docs.localstack.cloud/user-guide/localstack-enterprise/k8s-operator/) & [Executor](https://docs.localstack.cloud/user-guide/localstack-enterprise/kubernetes-executor/))” → “Kubernetes Pack ([Operator](https://docs.localstack.cloud/user-guide/localstack-enterprise/k8s-operator/) & [Executor](https://docs.localstack.cloud/user-guide/localstack-enterprise/kubernetes-executor/))”
=> docs: update line item in both tables for K8 Pack

.markdownlint-cli2.yaml
[Markdownlint version 0.38](https://github.com/DavidAnson/markdownlint/blob/224987d727ebada36752074d2466a061c9e03ff0/CHANGELOG.md#0380) introduced a new rule `MD059`.
This rule fails on several lines on the current `main`:
```
$ make lint
markdownlint-cli2 --fix
markdownlint-cli2 v0.18.0 (markdownlint v0.38.0)
Finding: content/**/*.md !node_modules !content/en/tutorials/cloud-pods-collaborative-debugging/* !content/en/user-guide/integrations/terraform/* !content/en/user-guide/aws/events/* !content/en/references/coverage/_index.md !content/en/getting-started/installation.md
Linting: 393 file(s)
Summary: 14 error(s)
content/en/references/configuration.md:174:107 MD059/descriptive-link-text Link text should be descriptive [Context: "[here]"]
content/en/user-guide/aws/athena/index.md:117:83 …
```
=> exclude MD059 from markdownlint

content/en/user-guide/web-application/accounts/index.md
This PR fixes linting violations introduced in #1768
=> Fix linting

content/en/references/configuration.md, content/en/user-guide/aws/kinesis/index.md
Document the newly introduced Kinesis Mock Scala engine in addition to a small section on performance tuning of the Kinesis service.
- Add documentation for flags introduced in https://github.com/localstack/localstack/pull/12559
- Adds a small section on performance tuning -- with focus on using the new Scala engine.
=> add(kinesis): Include new Scala engine and performance section

content/en/user-guide/integrations/aws-cdk/index.md
I believe that [this](https://github.com/localstack/aws-cdk-local?tab=readme-ov-file#version-support) should be on our aws-cdk-local's public documentation. Currently, this information it's hard to find and we're seeing multiple tickets on supports related to this specific use case.
=> Aws cdk local limitations update edu

content/en/user-guide/aws/rds/index.md
Before recent changes, using `postgres` as database name for an RDS postgres database lead to unexpected errors.
Now, it should work, but we would still like to encourage users to use a different database name.
* Clarify comment about `postgres` database name
=> Clarify RDS postgres database name restriction

content/en/user-guide/integrations/rancher-desktop/index.md, content/en/user-guide/lambda-tools/hot-reloading/index.md
This PR adds a clarification to the Rancher Desktop documentation for Windows users running LocalStack via WSL2.
Specifically, it documents that when using hot reloading for Lambda functions, paths to Lambda handlers must be specified using WSL2-compatible paths `/mnt/c/` rather than Windows-style paths `C:\`
Without this, volume mounting of the lambda code into the lambda container would fail with a unintelligible error.
Changes:
Added a note under the Windows section of the Rancher Desktop guide.
Included a code snippet showing the correct WSL2 path format.
Motivation:
Hot reloading is a key developer feature in LocalStack, and ensuring it works reliably in WSL2-based workflows improves developer experience and reduces setup friction.
=> Add note on WSL2 path formatting for hot reloading in Rancher Desktop on Windows

.github/bot_templates/PARITY_COVERAGE_DOCS_PR.md, .github/workflows/docs-parity-updates.yml
This PR updates the parity docs generation workflow to consume artifacts from GitHub following the migration from CircleCI to GitHub Actions.
**Testing**
Tested in a forked repository and locally yesterday morning; will run tests in this PR as well
=> CI: fix docs parity updates
